### ISSUE TITLE
Network module doesn't update after system suspend

### ISSUE THREAD

**Issue by Sqvid** [Alexays/Waybar#156]
Waybar version: 0.3.0

Steps needed to reproduce error:
1) Be connected to wifi
2) Suspend/Sleep system
On reboot wifi will have temporarily disconnected while the network card comes back online.
3) Notice that even on reconnection (either by waiting or using a tool like nmcli) the bar indicates that the system is still "Disconnected"

I believe that after a long delay the module eventually realises the internet is connected. Downgraded to version 0.2.3 and the issue disappears. Thank you for any assistance, this is a great project :)

**Comment by ianhattendorf** [comment]
This appears to be fixed in master. It looks like the libnl callback type was changed from `NL_CB_VALID` to `NL_CB_MSG_IN` for `0.3.0`, but has been changed back in 0ddcf26a.

**Comment by Alexays** [comment]
@ianhattendorf thank you for confirming that it works now :)
@Ogromny @Sqvid Can you also test? :)

**Comment by Sqvid** [comment]
@Alexays @ianhattendorf Thank you for the response. I have recompiled with 9317385 and 0ddcf26 but the issue persists. Unfortunately my knowledge of the codebase is non-existent so I apolgise for not being able to offer any further insight.

That said this isn't just a system suspend issue as my original post suggested. Running a 'nmcli connection down <connection>' immediately updates the bar. However enabling the connection again leaves the bar on "Disconnected". Let me know if there is any other information I can provide.

**Comment by ianhattendorf** [comment]
Yep, looks like I spoke too soon. It looks like there's a time period where I can put my computer to sleep, wait, wake it back up, and the network displays as connected correctly. However if I wait for a longer period of time in between, it won't display as connected on waking. When putting it to sleep, it always displays as disconnected before sleeping.

Additionally, running `nmcli connection down $network_name && sleep 5 && nmcli connection up $network_name` correctly updates the bar.

**Comment by Alexays** [comment]
@ianhattendorf Is it fixed with dc9fe04d1112698b2a3fac8f13a003039172b931?
It's a simple fix until we find the right one.

**Comment by ianhattendorf** [comment]
@Alexays Yep this works. I threw in some logging and it looks like after sleeping for ~4 hours and waking it took 4 retries to successfully retrieve the ifid.

**Comment by Alexays** [comment]
Okay, I got the bug, so it's definitely not fixed.

**Comment by ianhattendorf** [comment]
Interesting, it's been working perfectly for me these past few days. Does it happen consistently?

**Comment by Alexays** [comment]
Should be better with my lastest changes, someone can test?

**Comment by Sqvid** [comment]
Yeah d0370ac seems to have fixed the issue for me. Thank you :)

**Comment by Groggy** [comment]
I got the bug. After investigating a bit, it seems that it only appears when specifying `format-disconnected` in the configuration. So I looked at the code of `waybar::modules::Network::update()`, and from what I understand :
* when the network is disconnected, `format_` and `default_format_` are set to the `format-disconnected` if any
* when the network is reconnected, `format_` and `default_format_` are set to the `format-ethernet` if any but never to the default `format` if not

Maybe a mixup between `format_` and `default_format_`... Not sure how to fix it but hope this will help.

Looks like eace8c549fd5b0506435bf2bcadad0fd303d2e57 is the cause.

**Comment by Alexays** [comment]
Fixed with 1ccf372f8e9d74cb18e92220c18a0729832fe69e

**Comment by Alexays** [comment]
Can someone test if with the `network` branch this issue is still fixed?
(949a4ec)

**Comment by objectivephoenix** [comment]
@Alexays just wanted to mention that this issue is still present in Waybar 0.9.5

**Comment by Galicarnax** [comment]
Same here, but with MPD module (actually, the single module I use :) ). After waking the laptop from suspend, I need to restart waybar, as it does not respond to MPD status changes. Using latest version of waybar on Arch (v. 0.9.5-2)
