### ISSUE TITLE
Module visible if no bluetooth controller found

### ISSUE THREAD

**Issue by dadav** [Alexays/Waybar#1707]
**Version**

Waybar v0.9.13

**Expected behaviour**

When no bluetooth controller is found, nothing should be showed in the waybar.

**Current behaviour**

There is an empty string? in the waybar.

I see this error in the logs:

```journald
[2022-10-04 17:09:55.203] [error] findCurController() failed: no bluetooth controller found
```

**What I already tried**

I tried to set `format-disabled` to an empty string (like in the manpage), but it changes nothing.

The config was like this:

```json
   "bluetooth": {
    "format": "\uf294 {status}",
    "format-connected": "\uf294 {device_alias}",
    "format-connected-battery": "\uf294 {device_alias} {device_battery_percentage}%",
    "tooltip-format": "{controller_alias}\t{controller_address}\n\n{num_connections} connected",
    "tooltip-format-connected": "{controller_alias}\t{controller_address}\n\n{num_connections} connected\n\n{device_enumerate}",
    "tooltip-format-enumerate-connected": "{device_alias}\t{device_address}",
    "tooltip-format-enumerate-connected-battery": "{device_alias}\t{device_address}\t{device_battery_percentage}%"
    }, 
```

Relevant css:

```css       
* {                                                                                                                                                                          
    border: none;                                                                                                                                                            
    border-radius: 0;                                                                                                                                                        
    font-family: FontAwesome, Iosevka;                                                                                                                                       
    font-size: 14px;                                                                                                                                                         
    min-height: 0;                                                                                                                                                           
}
                                                                                                                                         
#bluetooth {
    padding: 0 10px;
    margin: 0 5px;
    background: #2980b9;      
}       
```

**Screenshot**

![image](https://user-images.githubusercontent.com/33197631/193860128-38a414af-8e15-46d8-a6fd-7e56fe1d8cd5.png)

**Comment by Alexays** [comment]
Fixed with be28ee3

**Comment by pzant** [comment]
v0.9.15 instead of hide module displays text "bluetooth"

**Comment by Firgen** [comment]
The module still shows an empty string in v0.9.16 if it has some padding set. When you update it, for example with a click event, it shows up as on or off.
