### ISSUE TITLE
warning: cannot resolve "libspdlog.so=1.11-64", a dependency of "waybar"

### ISSUE THREAD

**Issue by jstdk** [Alexays/Waybar#1779]
This pops up since today in Arch Pacman, and updating is not possible (even on force). Updating libspdlog in AUR is not possible (for me) as the current version is 1.03. 

warning: cannot resolve "libspdlog.so=1.11-64", a dependency of "waybar"

**Comment by ckcr4lyf** [comment]
Saw exact same thing right now:
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
resolving dependencies...
warning: cannot resolve "libspdlog.so=1.11-64", a dependency of "waybar"
:: The following package cannot be upgraded due to unresolvable dependencies:
      waybar
```

Current system:
```
$ uname -a
Linux arch 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 GNU/Linux
```

**Comment by caseyjp11** [comment]
spdlog is built with this:
/usr/lib/libspdlog.so
/usr/lib/libspdlog.so.1
/usr/lib/libspdlog.so.1.10.0

There is a version 1.11 of spdlog, but it is a recent build (6 days). My bet is the production version of waybar was built against the wrong spdlog version.

**Comment by someoneinjd** [comment]
In my opinion, this problem is caused by bad packaging by archlinux maintainers. `libspdlog.so=1.11-64` is now in the community-testing repository and has not been officially released. [Here is the related issue](https://bugs.archlinux.org/task/76492?project=5&string=waybar).

**Comment by caseyjp11** [comment]
> In my opinion, this problem is caused by bad packaging by archlinux maintainers. `libspdlog.so=1.11-64` is now in the community-testing repository and has not been officially released. [Here is the related issue](https://bugs.archlinux.org/task/76492?project=5&string=waybar).

Looks like spdlog (which the lib is a part of) hasn't been updated to the latest release version.

**Comment by bg2908** [comment]
Been able to upgrade the apps now. `spdlog` to `1.11.0` and `waybar` to `0.19.15-2`

But now waybar have this error and can't launch
`waybar: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory`

So I downgraded to `spdlog 1.10.0-3` and `waybar 0.9.15-1` for now

**Comment by jstdk** [comment]
Should be resolved by now. 

![image](https://user-images.githubusercontent.com/115603308/200772054-ac6d82eb-9653-4a66-9d82-203cb042acef.png)

**Comment by martinykrz** [comment]
I still have this issue that when I launch waybar it displays
`waybar: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory`

But I think I found a work around that doesn't require to downgrade `spdlog`
`sudo cp /usr/lib/libspdlog.so.1.11 /usr/lib/libspdlog.so.1`

I don't think it's the proper way to fix this issue but for the time been, it works.

**Comment by theotrst** [comment]
same/similar problem. 

`l'installazione di spdlog (1.12.0-1) interrompe la dipendenza 'libspdlog.so=1.11-64' richiesta da waybar-hyprland-git`

[installation of pdlog (1.12.0-1) interrupts the dependency 'libspdlog.so=1.11-64' requested by waybar-hyprland-git]

Apparently I cannot update anymore. Any idea? (Not sure I want to try the solution of martinykrz)

**Comment by zjeffer** [comment]
You should switch to waybar-git, waybar-hyprland-git is now obsolete.
