### ISSUE TITLE
Libappindicator tray

### ISSUE THREAD

**Issue by Alexays** [Alexays/Waybar#21]
Tray beta now shipped :)

Bugs I noticed:
- Menu not correctly positioned (also Tooltips) #63 
- ~~Support multi modules~~
- ~~With multiple apps in tray, only the last is interactive, the others cause crash~~

### Electron apps
You need `libappindicator-gtk3` (added to AUR package)
and launch apps with `env XDG_CURRENT_DESKTOP=Unity slack`

**Comment by Alexays** [comment]
Not at the moment, but it's a good feature to have :)

**Comment by jeremejevs** [comment]
I guess I'll report here, instead of spamming issues, since this a beta feature.

When restarting the bar, only Telegram and Keybase icons remain. Slack and Caprine are gone.

Also, Discord never appears at all, for some reason, even with the latest fixes.

**Comment by jeremejevs** [comment]
Upon further usage, it looks like Keybase doesn't re-appear consistently either, only sometimes.

Right-clicking the Keybase tray outright crashes the bar, every time. Other apps crash the bar too when right-clicking, but I can't consistently reproduce it.

Sometimes the bar fails to start. Can't consistently reproduce either, but it eventually happens after launching and killing it repeatedly (segfault, no special error).

Not sure if of any use, but when launching the bar I get these two:

```
An object is already exported for the interface org.kde.StatusNotifierWatcher at /StatusNotifierWatcher
GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Status Notifier Host with bus name ':1.308' and object path '/StatusNotifierHost' is already registered
```

**Comment by Alexays** [comment]
Do you have a multi-screen configuration?
And the fact that the slack icon doesn't change is normal, it's just that there's no code to manage the tray change 😆 
I can't reproduce the right click :/

**Comment by jeremejevs** [comment]
Yep, I see where this is going :slightly_smiling_face: I have two monitors, both have a bar.

**Comment by Alexays** [comment]
@jeremejevs Can your check if the crash is still present in the last commit? :)

**Comment by jeremejevs** [comment]
Yep, the issue is still there, unfortunately. I have also noticed that in some conditions, if the first icon you right-click on after launching Waybar is Keybase, then right-clicking on other icons still opens Keybase's tray menu. Had that happen with Telegram too. Peculiar.

**Comment by Alexays** [comment]
@jeremejevs I found time to work on it a little bit and it's normally fixed now :)

**Comment by jeremejevs** [comment]
Tested, no crashes, thanks! :slightly_smiling_face: 

Only issue remaining - no Discord icon.

**Comment by Alexays** [comment]
@rvi64 I didn't implement the icon updates, if I find time I will do it next week

**Comment by NokiDev** [comment]
Hi I don't know if I should create a specific issue, or if trail icons related issues are grouped here. 
Tell me and I'll create one.

issue : 
Some icons are large, (VLC in my case) and resizes the height of the bar to the height of the icon.
I didn't look, in the code yet, but it don't seems difficult to fix. 
I can look into it if needed just help me a bit to dive into the codebase.

**Comment by Alexays** [comment]
@NokiDev Oh, I thought I fixed it, so I'm watching it next week. :)

**Comment by cjbassi** [comment]
Also getting the large icon issue with Insync, but the rest work fine.

**Comment by Sandmonster** [comment]
@Alexays tray doesn't show up for me. How do I log this behavior?

**Comment by Sandmonster** [comment]
@Alexays nvm, nm-applet doesn't show up, everything else is as supposed to be

**Comment by mxmilkb** [comment]
I get the large icon/bar issue with `radiotray-ng`.

**Comment by Alexays** [comment]
Thanks for the functional example @mxmilkb it's now fixed with aeec80f3753cf63399e172944dc0015213f9eedd

**Comment by fmartingr** [comment]
On archlinux, with the system updated I'm not seeing the `nm-applet` nor `blueberry-tray` icons, any way to make sure they are compiled with the correct flag?

Also, the Telegram icon dissapear if I restart waybar (not sure if this has something to do with the updating icons).

Using both community/waybar and aur/waybar-git.

**Comment by tmstieff** [comment]
The AUR has a package "network-manager-applet-indicator" which compiles nm-applet with the correct flags. For bluetooth, blueman-applet works out of the box, but I'm not sure about the details regarding blueberry.

**Comment by fmartingr** [comment]
Thanks @tmstieff ! I've replaced blueberry with bluemon and that shows the icon, but the AUR package you say isn't showing up as expected, is [this one](https://aur.archlinux.org/packages/network-manager-applet-indicator/)?

**Comment by tmstieff** [comment]
That's the correct package. I forgot to mention that you'll need to pass `--indicator` on the exec command @fmartingr :

```
exec --no-startup-id 'nm-applet --indicator'
```

**Comment by fmartingr** [comment]
@tmstieff Oh, that did the trick! Thanks!

**Comment by mijoharas** [comment]
@tmstieff Should the right click functionality be working correctly with both of them?

**Comment by fmartingr** [comment]
@mijoharas Mine works but the overlay is shown centered on the screen rather tan on mouse cursor position.

**Comment by Alexays** [comment]
Thanks to @alebastr for finishing the tray implementation ❤️ 
PS: i'll create another issue for the `XEmbed proxy` and for the the overlay pb look at #63

**Comment by varac** [comment]
nm-applet works shows up fine in the tray, but [segfaults when trying to connect to unknown wifi networks](#303).

**Comment by jeremejevs** [comment]
Crashes when running TeamViewer 14. Need a display manager to reproduce though, since TeamViewer won't work without one. Certainly related to SNI:

```
Failed to create DBus Proxy for org.kde.StatusNotifierItem-11561-1 /StatusNotifierItem: std::bad_cast
```

**Comment by afk-mario** [comment]
![image](https://user-images.githubusercontent.com/1025751/71929321-055f3080-315f-11ea-89fa-015ee55c780e.png)

The popup from QT applications like the one in the image doesn't show on waybar.
I tried it with the app [ripcord](https://cancel.fm/ripcord/), I remember it working on polybar.

**Comment by apiraino** [comment]
> nm-applet works shows up fine in the tray, but [segfaults when trying to connect to unknown wifi networks](#303).

@varac linking the correct Gnome issue (for those experiencing the same issue)
https://gitlab.gnome.org/GNOME/network-manager-applet/issues/64

**Comment by hassec** [comment]
Can someone point me towards how I would go about figuring out why for example the blueberry-tray doesn't work with this? 

I assume there is some way waybar polls for info and a way tray-apps should publish there info?
If I want to waste my time debugging this, any hints where/how to start on this?
Thanks :)

**Comment by eoli3n** [comment]
Here if tray icon has a menu, it appears under window and is not clickable:
![20200514_15h46m59s_grim](https://user-images.githubusercontent.com/14223657/81942284-3adac580-95fa-11ea-8022-b6f322926324.png)

**Comment by luispabon** [comment]
If somebody stumbles upon this, `env XDG_CURRENT_DESKTOP=Unity SOME_ELECTRON_APP` is not necessary anymore. Slack works fine on the tray with that value set to `sway`.

**Comment by luispabon** [comment]
@eoli3n I believe that issue is fixed by https://github.com/swaywm/sway/commit/4a2729286695a96886d027c1d9ea92a270fc0781

**Comment by niktob560** [comment]
``sway 1.4`` ``libappindicator 12.10.0-14`` ``waybar v0.9.2`` issues with the menu under window exists

**Comment by luispabon** [comment]
@niktob560 as I mentioned earlier it's an issue with sway.

**Comment by niktob560** [comment]
``Waybar v0.9.3`` ``libappindicator 12.10.0.r296-1`` and ``sway 1.5`` issue with the menu under window does not existsts

**Comment by fauust** [comment]
Hi!
On debian bullseye (11), I can't see any electron app icons (Zulip, Element).
```console
❯ dpkg -l | grep -E '(sway|waybar|libappindicator)'
ii  gir1.2-appindicator-0.1:amd64                     0.4.92-8                            amd64        Typelib files for libappindicator1
ii  gir1.2-appindicator3-0.1:amd64                    0.4.92-8                            amd64        Typelib files for libappindicator3-1
ii  libappindicator-dev                               0.4.92-8                            amd64        allow applications to export a menu into the panel -- development
ii  libappindicator-doc                               0.4.92-8                            all          allow applications to export a menu into the panel -- documentation
ii  libappindicator1:amd64                            0.4.92-8                            amd64        allow applications to export a menu into the panel
ii  libappindicator3-1:amd64                          0.4.92-8                            amd64        allow applications to export a menu into the panel -- GTK3 version
ii  sway                                              1.5-7                               amd64        i3-compatible Wayland compositor
ii  sway-backgrounds                                  1.5-7                               all          Set of backgrounds packaged with the sway window manager
ii  swaybg                                            1.0-2                               amd64        Wallpaper utility for Wayland compositors
ii  swayidle                                          1.6-2                               amd64        Idle management daemon for Wayland
ii  swaylock                                          1.5-2                               amd64        Screen locker for Wayland
ii  waybar                                            0.9.4-1                             amd64        Highly customizable Wayland bar for Sway and Wlroots based compositors
```
I have tested various environment variables:
```console
❯ env | grep XDG
XDG_CURRENT_DESKTOP=sway
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=sway
XDG_SESSION_ID=12
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
```
Also `XDG_SESSION_DESKTOP=Unity`...

The following works though:
- Telegram
- blueman
- nm-applet
- nextcloud (not always).

**Comment by luispabon** [comment]
What is `XDG_SESSION_DESKTOP=Unity` supposed to fix anyway? I removed it from my environment some time ago and my tray works fine.

**Comment by fauust** [comment]
So, I am not sure if this was the reason (because I was trying to fix another problem with podman and cgroups rights), but I installed `dbus-user-session` and after a reboot I have now all my icons...

And @luispabon I have just tested removing all the `XDG env` variables, it works.

**Comment by kyak** [comment]
sparkleshare doesn't show the tray icon. Telegram, however, does.

What could be the problem?

**Comment by TheGreatestJannet** [comment]
> sparkleshare doesn't show the tray icon. Telegram, however, does.
> 
> What could be the problem?

I have the same issue with Nextcloud Client

![20220306_19h37m18s_grim](https://user-images.githubusercontent.com/51300636/156939259-21d672fa-0fe6-462e-8235-2a26e3f36bdd.png)

**Comment by 875d** [comment]
how to define icon theme for the tray? I cannot find a way in [the manual](https://man.archlinux.org/man/community/waybar/waybar-tray.5.en)

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment]
> how to define icon theme for the tray? I cannot find a way in [the manual](https://man.archlinux.org/man/community/waybar/waybar-tray.5.en)

@875d were you ever able to sort this out? I tried using `gsettings` as waybar seems to follow the GTK theme, but I'd like only to change the icons on the tray, not on every app

**Comment by 875d** [comment]
> > how to define icon theme for the tray? I cannot find a way in [the manual](https://man.archlinux.org/man/community/waybar/waybar-tray.5.en)
> 
> @875d were you ever able to sort this out? I tried using `gsettings` as waybar seems to follow the GTK theme, but I'd like only to change the icons on the tray, not on every app

No I didn't. I still have those horrible terrible icons.

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment]
> > > how to define icon theme for the tray? I cannot find a way in [the manual](https://man.archlinux.org/man/community/waybar/waybar-tray.5.en)
> > 
> > 
> > @875d were you ever able to sort this out? I tried using `gsettings` as waybar seems to follow the GTK theme, but I'd like only to change the icons on the tray, not on every app
> 
> No I didn't. I still have those horrible terrible icons.

Well, I just opened [this issue](https://github.com/Alexays/Waybar/issues/1957), which addresses our woes, in case you'd be interested.

**Comment by 0atman** [comment]
Still finding Sparkleshare without a tray icon, fyi. Thanks for the work here! :heart:

**Comment by AdsonCicilioti** [comment]
> > how to define icon theme for the tray? I cannot find a way in [the manual](https://man.archlinux.org/man/community/waybar/waybar-tray.5.en)
> 
> @875d were you ever able to sort this out? I tried using `gsettings` as waybar seems to follow the GTK theme, but I'd like only to change the icons on the tray, not on every app

@7ff04da4aa6ac37197e249299066ac30  Acredito que você deve definir alguma estratégia via variáveis CSS (gtk) para obter a alternância de cores seguindo o vamor da chave `color-scheme` do schema  `org.gnome.desktop.interface` usando `gsettings`.

**Comment by pfsalminen** [comment]
Is there a way to specify certain icons to hide or show in the try? If not, is this a possible feature?

**Comment by dexslender** [comment]
i'm using [youtube-music Desktop](https://github.com/th-ch/youtube-music) and its icon is displayed correctly but when it tries to display the tooltip logs this error:
```
(waybar:14052): Gtk-WARNING **: 11:40:26.500: Failed to set text 'YouTube Music: deadmau5 & Kaskade - I Remember' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

**Comment by victorballester7** [comment]
Hello,
I am not able to make my tray appear in my waybar. I have the package `libappindicator-gtk3`installed and I even tried exporting the variable `XDG_CURRENT_DESKTOP=Unity slack` but still doesn't work.

Do you have an idea on where may the problem come from?

I am on archlinux.

Thanks in advance!

**Comment by victorballester7** [comment]
Hi! thanks for your answer @jman-schief. 

Actually I also tried with `sway` only but it didn't work either... :(

**Comment by victorballester7** [comment]
The problem was that I didn't start the processes nm-applet and blueman-applet, and so I could not see the wifi and blutooth images.

I have though another question. Is it possible to customize the style of the traybar, changing the colors of the icons (or even the icons themselves). I found that there is a hidden config that do some styling:
```
tray menu {
   background-color: red;
  border-radius: 15px;
}
```
How can I know all the available options for the styling of the tray a part from `menu`? Thank you in advance! :)

**Comment by apiraino** [comment]
@victorballester7 here the wiki documentation for the [tray CSS](https://github.com/Alexays/Waybar/wiki/Module:-Tray) option. Unsure if you can style the icons themselves, I suspect Waybar cannot intervene in other applications (see also #3328 )
