### ISSUE TITLE
Customize CPU icons independently

### ISSUE THREAD

**Issue by tmarti2** [Alexays/Waybar#2273]
Hi,
I'm using waybar to display all my cores current usage, and I wanted to know if it was possible to customize each icon style individually ? for example updating color for warning/critical of each cores.

Thanks

**Comment by apiraino** [comment]
You cannot customize each CPU core _independently_ but you can configure _all_ cpu cores to show different colors according to their `state`, example:

confiig file
```
    "cpu": {
        "format": "{icon0} {icon1} {icon2} {icon3} {icon4} {icon5} {icon6} {icon7}",
        "format-icons": ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"],
        "states": {
            "idle": 0,
            "normal": 10,
            "warning": 30,
            "critical": 75
        }
    },
```

And `style.css`
```
#cpu.idle {
  color: grey;
}

#cpu.normal {
  color: green;
}

#cpu.warning {
  color: yellow;
}

#cpu.critical {
  color: red;
}
```

(sorry if i misinterpreted your question)

**Comment by tmarti2** [comment]
Thanks for your reply.
That's what I thought, it's only possible to change all their styles at the same time :/
Thanks again.

**Comment by redtide** [comment]
I haven't tried yet but the [wiki](https://github.com/Alexays/Waybar/wiki/Module:-CPU#format-replacements) mention about `{iconN}` and `{usageN}`, with `N` as the core number.

**Comment by tmarti2** [comment]
That's for the config file, to either display % value or icon for each core independently, but my question was about the style.css file, if it was possible to customize each value/icon independently. I didn't found a way to use iconN/usageN in the css file, but maybe I missed something ?

**Comment by tmarti2** [comment]
You are a genius, I didn't think about this ! Thanks a lot

**Comment by redtide** [comment]
Looking at apiraino' and wiki' example looks like iconN is about the format used to display an icon for the current state of the same cpu, though the wiki also mentions "cpu core", I'm a bit confused, so maybe I got it wrong.

**Comment by redtide** [comment]
> You are a genius, I didn't think about this ! Thanks a lot

Hope it will work, let us know!

**Comment by tmarti2** [comment]
```
"cpu": {
        "interval": 1,
        "format": "{icon0}{icon1}{icon2}{icon3}{icon4}{icon5}{icon6}{icon7}{icon8}{icon9}{icon10}{icon11}{icon12}{icon13}{icon14}{icon15}",
        "format-icons": [
            "<span color='#69ff94'>▁</span>", // green
            "<span color='#2aa9ff'>▂</span>", // blue
            "<span color='#f8f8f2'>▃</span>", // white
            "<span color='#f8f8f2'>▄</span>", // white
            "<span color='#ffffa5'>▅</span>", // yellow
            "<span color='#ffffa5'>▆</span>", // yellow
            "<span color='#ff9977'>▇</span>", // orange
            "<span color='#dd532e'>█</span>"  // red
        ]
    }
```
It works ! I didn't think about directly setting icon colors here with span, thanks !

**Comment by apiraino** [comment]
amazing, TIL :)

wouldn't be great to document this in the [Wiki](https://github.com/Alexays/Waybar/wiki/Module:-CPU)? :innocent:

**Comment by redtide** [comment]
> wouldn't be great to document this in the [Wiki](https://github.com/Alexays/Waybar/wiki/Module:-CPU)? innocent

I got that information after a search in issues, [here](https://github.com/Alexays/Waybar/issues/50#issuecomment-440790013), but yeah, this should be documented explicitly in the wiki, but not only for the `cpu` module, it's a generic setting. It should mention also about [PangoMarkupFormat](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html#PangoMarkupFormat), though IDK if it's something reserved to developers only and where it could be better to fit in there. @Alexays?

**Comment by Alexays** [comment]
Sure, you can update the wiki to add more informations about that.
We already have a section about pango markup (https://github.com/Alexays/Waybar/wiki/Configuration#module-format)
But we can improve it.

**Comment by redtide** [comment]
@apiraino @Alexays I fixed the link to PangoMarkupFormat documentation in [Configuration#module-format](https://github.com/Alexays/Waybar/wiki/Configuration#module-format) (and added some css code block language type) and added the @tmarti2 code above as an example for the [cpu](https://github.com/Alexays/Waybar/wiki/Module:-CPU#examples) module page

**Comment by tmarti2** [comment]
Well, my problem is back, using span was a trick which worked in my case, but if now I want to do something similar to temperature :
```json
"temperature": {
        "thermal-zone": 2,
        "tooltip": false,
        "on-click": "kitty gotop -c monokai -p",
        "format": "{icon} {temperatureC}°C",
        "format-icons": [
            "<span color='#69ff94'></span>", // green
            "<span color='#2aa9ff'></span>", // blue
            "<span color='#ffffa5'></span>", // yellow
            "<span color='#ff9977'></span>", // orange
            "<span color='#dd532e'></span>"  // red
        ],
    },
```
Here the problem is that only the icon color is affected, the temperature in °C stays white. Its color can be change by either adding a span inside format (but then you can only choose 1 color), or using css
```css
#temperature{
    color: #69ff94; //green
}
```
Their is a critical field which allows to choose a value above which you can change the color, but that's only 2 colors.
In this case is there a workaround ?

**Comment by redtide** [comment]
I have no idea, IMHO I wouldn't change the color of the font, which should be the same for all modules, I just like see colored icons.
