### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Gigadoc2** [Alexays/Waybar#238]
Currently, the network module seems to only be capable of displaying an ipv4 address.

It should probably also be able to display the currently preferred ipv6 address, as ipv6 is now widely deployed with at least some ISPs in certain countries.

With IPv6 there are usually multiple addresses per interface, so it might make sense to copy the approach used by i3status: Instead of displaying one of the addresses of the current interface, there could be just a separate ipv6 module that displays the currently preferred ipv6 address of the entire host. Maybe not ideal for all use cases, but that could be easier to implement on a global level instead of per-interface :smile:

**Comment by Alexays** [comment]
@Gigadoc2 can you test with #319 and set in your network config `"family": "ipv6"`? :)

**Comment by Gigadoc2** [comment]
Apologies for the delay.
I tested it, but it behaves a bit weird:

![screenshot](https://user-images.githubusercontent.com/1494790/58656692-48753d80-830c-11e9-8d7a-415752aece0f.png)

This is the result of the following config:
```json
    "network#bond": {
        "interface": "bond0",
        "family": "ipv6",
        "format": " {ipaddr}/{cidr}",
        "tooltip": false
    },
```

The `::` in the front should not be there, the address is cut short (it should be `fd76:b436:28bc:32:a1a6:25a8:d255:174e`), and the prefix size is `64`, not `0`.

Then there is also the matter of address selection: The address chosen here is a privacy-extension generated address (so, an address with limited lifetime which is only used for outgoing connections, not something you would connect to), and it is from the ULA space (so, a private address) while the system is also assigned a globally routable address.
The address chosen by waybar is also the first one appearing in the output of `ip a`, I suspect a connection there (it is probably also the first one sent over netlink?)

i3status somehow manages to always figure out the most useful adress: The global, non-temporary address assigned via DHCP or SLAAC. But I don't know how it does so, and it might be very complicated.

**Comment by Alexays** [comment]
Should be fixed with latest versions

**Comment by auroraanna** [comment]
i'm on v0.10.2 and this is still an issue. when connected to wifi (didn't test ethernet) the network module shows "Disconnected" when the computer doesn't have a public ipv4 address, only an ipv6 address.

Even though it says "Disconnected", i was very much not as i could ping `ipv6.google.com`.

**Comment by hb9hnt** [comment]
I'm still experiencing the same issue with the default setup on OpenSUSE Tumbleweed using waybar 0.11.0. I use a IPv6-only Wifi with NAT64/DNS64 and clatd for 464xlat. With this setup my IPv4 (via CLAT) and my IPv6 connectivity works just fine. However, waybar still shows the wifi as disconnected.

Maybe this is worth another (open) issue?
