### ISSUE TITLE
Network module appears like it's connected when the radio is off

### ISSUE THREAD

**Issue by fybx** [Alexays/Waybar#2416]
Here's a quick breakdown of how I stumbled across this issue:

When I turn the WLAN radio off using `nmcli radio all off`, the network interface ignores `format-disconnected: ""` statement and shows the icon like it's connected.

The logic behind detecting if the module is connected in waybar is buggy, but I haven't been able to read and test the code myself.

PS: turning on the radio (`nmcli radio all on`) but not connecting to any station works as expected; the icon does not appear.

**Comment by Fabian-G** [comment]
Can confirm. I have waybar configured so that it toggles `nmcli radio wifi on|off` on right click. When it shows `format-wifi` and I click once it goes to `format-disconnected` instead of `format-disabled` as expected.

Left-clicking on the module shortly after it switched to `format-disconnected` brings it to `format-disabled` though.

**Comment by fybx** [comment]
@Fabian-G, using your issue, I was able to correct mine. I added `"format-disabled": ""` to my module settings, and now when I toggle the radio switch off, the module disappears as I expected.

About your issue, maybe when you click on the icon
1. waybar sends the command
2. command first causes the disconnection
3. waybar checks network status, status is disconnected
4. waybar displays `format-disconnected`
5. radio is switched off
6. waybar won't update to `format-disabled` until next poll

And if you click on the module again:
1. waybar checks network status, status is radio off
2. waybar shows `format-disabled`

You can try setting `interval` to 5 seconds to see if my hypothesis holds.

**Comment by Fabian-G** [comment]
Unfortunately this doesn't do the trick. Even with `interval` set to a low value it stays at `format-disconnected`.

However, I noticed that when I explicity set the `interface` value in the module to my wireless interface even clicking on it won't change anything. It just stays at `format-disconnected` forever.

Looking at the code it seems to me like the only way it ever gets to `format-disabled` is with rfkill support.

https://github.com/Alexays/Waybar/blob/b7a527b122831235fb36f661d415f5f3ed378d92/src/modules/network.cpp#L280-L291

Right-clicking on the module also correctly emits an event on `rfkill event` with `soft=1`:

```
2023-08-24 12:08:19,477527+02:00: idx 3 type 1 op 2 soft 1 hard 0
```

If I understand the code correctly this should resullt in `rfkill_.getState()` returning `true` and I suspect it doesn't. But I can't verify this, because the code doesn't compile on my machine for some reason.
Another suspicion would be that Arch just ships waybar without rfkill support, but I don't know how to verify this either.

@fybx Which distribution do you use, if you don't mind me asking?

**Comment by Fabian-G** [comment]
I'll also leave the relevant parts of my config here in case I'm just being stupid:
`$HOME/.config/waybar/scripts/toggleWifi.sh` just runs `nmcli radio wifi off` (or `on` depending on the state).
```json
"network": {
      "interface": "wlp4s0",
      "format-wifi": "{icon} connected",
      "tooltip-format-wifi": "{essid}",
      "format-linked": "󰤩 (No IP)",
      "format-disconnected": "󰤨  on",
      "format-disabled": "󰤭  off",
      "format-icons": [ "󰤟 ", "󰤢 ", "󰤥 ", "󰤨 "],
      "on-click": "swaymsg exec \\$network-config",
      "on-click-right": "$HOME/.config/waybar/scripts/toggleWifi.sh"
}
```
This is the config where `format-wifi`, `format-linked` and `format-disconnected` work as expected.
But when the WiFi is on and I run `nmcli radio wifi off` waybar goes to `format-disconnected` (instead of `format-disabled`) and stays there. Left clicking on the module, waiting the default interval of 60s or reloading sway don't have any effect. 
Where it gets really weird is that when I reboot with wifi turned *off*, after startup waybar will show `format-linked`, although `nmcli radio wifi` still shows disabled.

**Comment by winkelnp** [comment]
This is most likely fixed by #4260, could someone who has/had this issue check?

**Comment by vecchioBlister** [comment]
Still happening on Waybar v0.14.0, Alpine edge 3.23.0_alpha20250612, Linux 6.12.47-0-lts x86-64 musl libc. The configuration is the same as above. The first screenshot depicts iwgtk showing the interface disabled, rfkill showing phy0 (wlan0) disabled, while Waybar displays a made-up signal strength and an enabled/on state; the second screenshot depicts the same Waybar on another monitor, with no signal strength, yet still an enabled/on icon.

![Image](https://github.com/user-attachments/assets/fa59d32b-6c5c-4224-940d-923fc4351b82)
![Image](https://github.com/user-attachments/assets/098f82e8-3f4e-4289-985f-7fd717e88a2b)
