### ISSUE TITLE
upower module taking space while empty, until clicked

### ISSUE THREAD

**Issue by marcelohdez** [Alexays/Waybar#2504]
https://github.com/Alexays/Waybar/assets/76508651/3f771a4a-2e24-45ed-a8ab-fdc0f6cbdc99

I have this module enabled on both my PC and laptop dots, and even though `hide-if-empty` is in its default of `true` the module takes up blank space until clicked on my desktop with no batteries.

**Comment by Alexays** [comment]
Should be fixed with 5319cb6e

**Comment by marcelohdez** [comment]
This problem still persists running Waybar 0.9.24 on Fedora 39, on my _desktop_ PC. I _do_ have the UPower service running according to systemd, but there are no batteries; the output of `upower -d` gives:
```
Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              Sat 02 Dec 2023 12:18:37 AM EST (43 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    percentage:          0%
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  1.90.2
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: PowerOff
```
yet the upower module still stays blank until clicked, in which case it disappears.
