### ISSUE TITLE
Segmentation fault when clicking on sway workspace

### ISSUE THREAD

**Issue by ainola** [Alexays/Waybar#291]
I'm finding that clicking on any of my sway outputs will eventually crash Waybar as of 0.6. It's often not an immediate thing; The bar will crash after some light use. This is on Arch Linux.

**Comment by forkbomb9** [comment]
Happens to me too

**Comment by ainola** [comment]
A bisect suggests that cccf60c30ec093362bc2c825dc8ccb9316d6bb32 is the commit that introduced this issue.

**Comment by betseg** [comment]
Happens to me too, I think it happens when title text switches too quickly (like switching browser tabs quickly, or switching workspaces quickly).

**Comment by Alexays** [comment]
Can anyone give me a bt with debug symbols? :)

**Comment by Alexays** [comment]
Fixed with d027243a19997b24a26ae962e28ccdbe434a1153

**Comment by betseg** [comment]
Still happens for me on 0.6.1.

`bt` with debug symbols:

```
#0  0x0000000000000001 in  ()
#1  0x00007ffff6f51538 in  () at /usr/lib/libgtk-3.so.0
#2  0x00007ffff6efa4e8 in  () at /usr/lib/libgtk-3.so.0
#3  0x00007ffff716b05d in gtk_widget_size_allocate_with_baseline ()
    at /usr/lib/libgtk-3.so.0
#4  0x00007ffff6ef8558 in  () at /usr/lib/libgtk-3.so.0
#5  0x00007ffff6ef90e5 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff6f5152a in  () at /usr/lib/libgtk-3.so.0
#7  0x00007ffff6efa4e8 in  () at /usr/lib/libgtk-3.so.0
#8  0x00007ffff716b05d in gtk_widget_size_allocate_with_baseline ()
    at /usr/lib/libgtk-3.so.0
#9  0x00007ffff7181ad4 in  () at /usr/lib/libgtk-3.so.0
#10 0x00007ffff6af8e75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff6ae6188 in  () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff6aea1ae in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff6aeb080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff716b3d0 in gtk_widget_size_allocate_with_baseline ()
    at /usr/lib/libgtk-3.so.0
#15 0x00007ffff7182390 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff6aea3b5 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff6aeb080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff6f46001 in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff6af8e75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff6ae5fd5 in  () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff6aea1ae in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff6aeb080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff6d2059b in  () at /usr/lib/libgdk-3.so.0
#24 0x00007ffff6d0ac3b in  () at /usr/lib/libgdk-3.so.0
#25 0x00007ffff6a08e53 in  () at /usr/lib/libglib-2.0.so.0
#26 0x00007ffff6a09661 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#27 0x00007ffff6a0b739 in  () at /usr/lib/libglib-2.0.so.0
#28 0x00007ffff6a0b77e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#29 0x00007ffff6bc3f5e in g_application_run () at /usr/lib/libgio-2.0.so.0
#30 0x00005555555b92f5 in waybar::Client::main(int, char**)
    (this=0x5555556c48a0, argc=1, argv=0x7fffffffe2a8) at ../src/client.cpp:267
#31 0x00005555555afae5 in main(int, char**) (argc=1, argv=0x7fffffffe2a8)
    at ../src/main.cpp:22
```

**Comment by betseg** [comment]
Still happens to me on 0.6.1 (on Arch).

`bt` with debug symbols:

```
#0  0x0000000000000002 in  ()
#1  0x00007ffff6f51538 in  () at /usr/lib/libgtk-3.so.0
#2  0x00007ffff6efa4e8 in  () at /usr/lib/libgtk-3.so.0
#3  0x00007ffff716b05d in gtk_widget_size_allocate_with_baseline () at /usr/lib/libgtk-3.so.0
#4  0x00007ffff6ef8558 in  () at /usr/lib/libgtk-3.so.0
#5  0x00007ffff6ef90e5 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff6f5152a in  () at /usr/lib/libgtk-3.so.0
#7  0x00007ffff6efa4e8 in  () at /usr/lib/libgtk-3.so.0
#8  0x00007ffff716b05d in gtk_widget_size_allocate_with_baseline () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff7181ad4 in  () at /usr/lib/libgtk-3.so.0
#10 0x00007ffff6af8e75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff6ae6188 in  () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff6aea1ae in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff6aeb080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff716b3d0 in gtk_widget_size_allocate_with_baseline () at /usr/lib/libgtk-3.so.0
#15 0x00007ffff7182390 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff6aea3b5 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff6aeb080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff6f46001 in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff6af8e75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff6ae5fd5 in  () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff6aea1ae in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff6aeb080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff6d2059b in  () at /usr/lib/libgdk-3.so.0
#24 0x00007ffff6d0ac3b in  () at /usr/lib/libgdk-3.so.0
#25 0x00007ffff6a08e53 in  () at /usr/lib/libglib-2.0.so.0
#26 0x00007ffff6a09661 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#27 0x00007ffff6a0b739 in  () at /usr/lib/libglib-2.0.so.0
#28 0x00007ffff6a0b77e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#29 0x00007ffff6bc3f5e in g_application_run () at /usr/lib/libgio-2.0.so.0
#30 0x000055555557b4c3 in waybar::Client::main(int, char**) (this=this@entry=0x55555563e8a0, argc=<optimized out>, argc@entry=1, argv=<optimized out>, 
    argv@entry=0x7fffffffe2a8) at ../src/client.cpp:267
#31 0x0000555555579fb4 in main(int, char**) (argc=1, argv=0x7fffffffe2a8) at ../src/main.cpp:22
```

**Comment by Alexays** [comment]
Anyone able to give me a way to reproduce the problem that works every time?

**Comment by Alexays** [comment]
Does 5a44c8c6debcf92722f6920b81ed44db8736a5da fix the issue?

**Comment by ainola** [comment]
I haven't had an issue since the upgrade so I cannot test, unfortunately.

**Comment by betseg** [comment]
Yes, it does fix the issue for me.

> Does [5a44c8c](https://github.com/Alexays/Waybar/commit/5a44c8c6debcf92722f6920b81ed44db8736a5da) fix the issue?
