### ISSUE TITLE
waybar displaying wrong timezone

### ISSUE THREAD

**Issue by Kommynct** [Alexays/Waybar#3024]
timedatectl outputs the following:

```
               Local time: Sun 2024-03-17 20:16:08 EDT
           Universal time: Mon 2024-03-18 00:16:08 UTC
                 RTC time: Mon 2024-03-18 00:16:09
                Time zone: America/Indiana/Indianapolis (EDT, -0400)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

However, after the new update, waybar is now saying it is currently midnight.

**Comment by ordy** [comment]
Don't know if you have a timezone set in your config file, but maybe try to first set your time zone with timedatectl because it looks like your output isn't reporting any.

**Comment by Kommynct** [comment]
it is set, I just removed it for privacy, should've said that

also, it worked perfectly before the most recent update. I currently have the timezone force set in waybar as a workaround, but I don't think I should have to set the timezone.

**Comment by ndcontini** [comment]
I'd like to chime in an say that I'm also facing this issue. It was working perfectly up until the update and now it only displays UTC instead of my timezone.

**Comment by itaranto** [comment]
Same here, `clock` displays UTC instead of my local timezone.

**Comment by vdpbl** [comment]
same, waybar-clock displays hwclock (utc by default but responds to time/date changes in uefi)

**Comment by itaranto** [comment]
> same, waybar-clock displays hwclock (utc by default but responds to time/date changes in uefi)

I didn't know that. 

But I have my hwclock synced with my OS clock anyway, both are set to my local timezone.

**Comment by Kommynct** [comment]
this is not correct, my hwclock is not displaying UTC and waybar still does not display the correct timezone unless manually set.

**Comment by jsaern** [comment]
I have the opposite challenge using Waybar v.0.9.9 on Ubuntu 22.04.  I only see my timezone's time when I want to see UTC.  

I have tried the following timezone settings:
1. `"timezone": "UTC"`
2. `"timezone": "Universal"`
3. `"timezone": "GMT"`
4. `"timezone": "UCT"`

![20240401-230805_grim](https://github.com/Alexays/Waybar/assets/24497145/7146a3ca-1217-4816-a825-60642a8f0f45)

**Comment by Kommynct** [comment]
Try updating to v0.10

**Comment by itaranto** [comment]
> Issue still remains with `Waybar v0.10.2`. Workaround is manually set the timezone in `~/.config/waybar/config`:
> 
> ```
>     "clock#date": {
>         "timezone": "America/Argentina/Buenos_Aires",
>         "format": "{:%A %b %d}",
>         "format-alt": "{:%Y-%m-%d}",
>         "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
>         "interval": 60
>     },
>     "clock#time": {
>         "timezone": "America/Argentina/Buenos_Aires",
>         "format": "{:%H:%M:%S}",
>         "interval": 1
>     },
> ```

Yup, this should be marked as a regression IMO.

**Comment by malmerri42** [comment]
This issue still persists with 10.4-2

**Comment by Blazing-Blast** [comment]
Even with `"timezone": "Europe/Amsterdam"`, I still only see UTC, and not UTC+2.
On waybar 0.10.4-2 (Arch).

**Comment by alxchk** [comment]
Looks like waybar doesn't work with sys-libs/timezone-data-2024b, at least have same issue with waybar at gentoo.
Masked 2024b until fixed.

**Comment by samuelcordero** [comment]
I'm currently facing the same issue:
![2024-09-08-134609_hyprshot](https://github.com/user-attachments/assets/46a7864c-7a82-4aeb-b8f5-9bbcf64e0cb5)

Although I'd swear this behavior wasn't there last week and the time displayed my timezone, I'm not sure. Maybe this bug only appears when certain time conditions are met? This issue had been silent for months, but today there are three reports of it. I'll post updates if it resolves itself without any specific updates addressing the issue.

**Comment by adnanzareef** [comment]
Mine is not working either, the debug log is saying : `[2024-09-08 17:55:58.688] [warning] Timezone: Asia/Dhaka. std::chrono::tzdb: cannot locate zone: Asia/Dhaka`

**Comment by SimeonVutov** [comment]
I am also facing the same problem. Waybar clock is using Universal time instead of my local time

**Comment by Fennix900** [comment]
Same issue here:

Waybar v0.10.4

i tried following configs 
`"timezone": "Europe/Vienna"`
`"timezone": "Europe/Vienna (CEST, +0200)"`

and i also tried to reconfigure hwclock

no success

`timedatectl 
               Local time: Sun 2024-09-08 15:47:00 CEST
           Universal time: Sun 2024-09-08 13:47:00 UTC
                 RTC time: Sun 2024-09-08 13:47:00
                Time zone: Europe/Vienna (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no`

![image](https://github.com/user-attachments/assets/1602e31a-1db4-4149-b15b-6308a00106cf)


i remember waybar showing the correct time some weeks ago

**Comment by itshog** [comment]
> Looks like waybar doesn't work with sys-libs/timezone-data-2024b, at least have same issue with waybar at gentoo. Masked 2024b until fixed.

I have the same issue on Arch Linux, and I can confirm that downgrading the package `tzdata` from 2024b-1 to 2024a-2 fixes the problem. I suggest this as a temporary workaround for now.

**Comment by itshog** [comment]
[Here](https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/IZ7AO6WRE3W3TWBL5IR6PMQUL433BQIE/)'s the changelog from 2024a to 2024b. It seems that something changed in the naming of the timezones, as in the changelog it says

>    System V names are now obsolescent.
     The main data form now uses %z.

Maybe this is useful to debug the issue?

**Comment by itaranto** [comment]
> Mine is not working either, the debug log is saying : `[2024-09-08 17:55:58.688] [warning] Timezone: Asia/Dhaka. std::chrono::tzdb: cannot locate zone: Asia/Dhaka`

I don't even see any log message, not even with `--log-level trace`. I'm on Arch Linux.

**Comment by Nick82285** [comment]
> Looks like waybar doesn't work with sys-libs/timezone-data-2024b, at least have same issue with waybar at gentoo. Masked 2024b until fixed.

Yeah, This is it. Arch homies should downgrade too, until there's some more communication on this bug. I don't know which package contains/modifies timezone data on Arch though, as it might be subsumed in a larger package. I just downgraded the package on Gentoo and restarted waybar.

**Comment by alexlnkp** [comment]
> > Looks like waybar doesn't work with sys-libs/timezone-data-2024b, at least have same issue with waybar at gentoo. Masked 2024b until fixed.
> 
> I have the same issue on Arch Linux, and I can confirm that downgrading the package `tzdata` from 2024b-1 to 2024a-2 fixes the problem. I suggest this as a temporary workaround for now.

Can confirm, works like a charm after the downgrade!

**Comment by themarcman314** [comment]
> > Looks like waybar doesn't work with sys-libs/timezone-data-2024b, at least have same issue with waybar at gentoo. Masked 2024b until fixed.
> 
> I have the same issue on Arch Linux, and I can confirm that downgrading the package `tzdata` from 2024b-1 to 2024a-2 fixes the problem. I suggest this as a temporary workaround for now.

Same here, downgrading to 2024a-2 fixes the issue.

**Comment by ruchir-k** [comment]
facing the same issue from today on arch

**Comment by ronasimi** [comment]
Same issue on arch, downgrading 2024b to 2024a-2 fixes - Arch Linux

**Comment by grimwaldr** [comment]
Also confirming that on Arch tzdata is the culprit - downgrade to fix.

**Comment by Nikola13377** [comment]
Also confirming that downgrading tzdata is the way to fix it on Arch

**Comment by hariseldon78** [comment]
another workaround is a custom module: 
```        
"custom/clock": {
          "exec": "date +\"%F %H:%M\"",
          "interval": 10
},
```

**Comment by sev7nsev7n7** [comment]
adding on that downgrading tzdata solves the issue on arch, hope this can be looked into soon

**Comment by Linuxadmn4718** [comment]
Seeing the same issue this morning. RTC is set to UTC and clock is only displaying UTC.

```
❯ timedatectl
               Local time: Mon 2024-09-09 13:33:07 PST
               Universal time: Mon 2024-09-09 05:33:07 UTC
               RTC time: Mon 2024-09-09 05:33:07
               Time zone: Asia/Manila (PST, +0800)
System clock synchronized: yes
              NTP service: active
              RTC in local TZ: no
```

**Comment by Kurumi0007** [comment]
hello, same here.
After downgrading, it works correctly

**Comment by enabwds** [comment]
I was facing the same issue. It seems that the only way to fix it is to downgrade tzdata. I use arch btw.

**Comment by itaranto** [comment]
I don't think downgrading a package is a good idea. But anyway, we aren't discussing Arch Linux here.

In my case I've been having this issues for several months, are we sure this is just tzdata?

Also, I have another machine running Fedora 40 and I experience the same issue, the tzdata version here is 2024a.

**Comment by enabwds** [comment]
I'm not entirely sure about Fedora as i have no experience with it or it's derivatives. In my case the only fix that worked was to downgrade tzdata from 2024b-1 to 2024a-2. I have no clue about why you would be having the issue for several months as i had only experienced the issue after updating a few hours ago.

**Comment by furadnik** [comment]
@itaranto You might have a different issue then? I'm also running Arch, downgraded tzdata, and it's working. Also it stopped working at the same time I upgraded tzdata to 2024b-1.

**Comment by itaranto** [comment]
> @itaranto You might have a different issue then? I'm also running Arch, downgraded tzdata, and it's working. Also it stopped working at the same time I upgraded tzdata to 2024b-1.

Yes, it's most likely a different issue.

I'm having this issue since version `v0.10`, just like the OP.

**Comment by charlesneimog** [comment]
same for me. I am on waybar `0.10.4`.

**Comment by DevZiaus** [comment]
I am also having the same issue. I am on waybar 0.10.4
My config:
"clock": {
        "timezone": "Asia/Dhaka",
        "format": "{:%I:%M%p}",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        // START CLOCK FORMAT
        "format-alt": "{:%Y-%m-%d}"
    },

**Comment by Nj0be** [comment]
Same issue on arch linux, downgrading tzdata fixes it.

**Comment by Erennedirlo** [comment]
Here to confirm downgrading tzdata to 2024a-2 fixes it

**Comment by J0nnyMak0** [comment]
In other words time is stuck at GMT. It would be nice if "timzone" supported a plus-minus syntax. So `"timezone": -5` would be equivalent to "America/Chicago" etc.

**Comment by Mahrjose** [comment]
Wait so it's because of the update!!
I spend 2 hours trying to fix it. I was going mad :)

**Comment by nomisreual** [comment]
> Looks like waybar doesn't work with sys-libs/timezone-data-2024b, at least have same issue with waybar at gentoo. Masked 2024b until fixed.

Can confirm downgrading `tzdata` resolved the issue for now.

**Comment by jeffreymonjacastro** [comment]
Downgrading `tzdata` resolved the bug for me also.

I installed downgrade with yay `yay -S downgrade`.
Then I run `sudo downgrade tzdata`, and I selected 2024a-2.
After that I run `pkill waybar & waybar &` to restart it.

**Comment by beeender** [comment]
https://github.com/chronotope/chrono-tz/releases/tag/v0.10.0

It seems chrono-tz `v0.10.0` fixed this.

**Comment by alexlnkp** [comment]
> https://github.com/chronotope/chrono-tz/releases/tag/v0.10.0
> 
> It seems `chrono-tz` `v0.10.0` fixed this.
> 
> ```
>    39       ╎ try {                                                                                                                                         
>    40       ╎   tzList_.push_back(locate_zone(zone_name.asString()));                                                                                       
>    41       ╎ } catch (const std::exception& e) {                                                                                                           
>    42       ╎   spdlog::warn("Timezone: {0}. {1}", zone_name.asString(), e.what());                                                                         
>    43       ╎ } 
> ```
> 
> ```
> (gdb) p e.what()
> $4 = 0x555555a79dd8 "std::chrono::tzdb: cannot locate zone: Asia/Shanghai"
> ```

The issue is fixed just by having 'chrono-tz' pkg?
Even if that's the case, there still is a regression from a previous version, which should be reported ideally. Did anyone do that yet?

**Comment by michael555444** [comment]
Same issue
Arch Linux: `6.10.9-arch1-1`
waybar: `0.10.4-2`
tzdata: `2024b-1`
waybar config:
```
		"clock":	{
			"interval":				1,
			"timezone":				"Europe/Moscow",	// Without manual tz set and with
			"tooltip-format":			"<tt><small>{calendar}</small></tt>",
			"format":				"{:%H:%M:%S}",
			"format-alt":				"{:%e %B %Y (%A) [%Y.%m.%d]}",
			"calendar":	{
				"mode":				"month",
				"mode-mon-col":			3,
				"on-scroll":			1,
				"format":	{
					"months":		"<span color='#ffead3'><b>{}</b></span>",
					"days":			"<span color='#ffffff'>{}</span>",
					"weekdays":		"<span color='#ffcc66'><b>{}</b></span>",
					"today":		"<span color='#ff6699'><b><u>{}</u></b></span>"
				}
			},
			"actions":	{
				"on-click-right":		"mode",
				"on-scroll-up":			"shift_up",
				"on-scroll-down":		"shift_down",
			},
			"on-click-middle":			"gnome-calendar"
		},
```

**Comment by aayan-infosec** [comment]
> Downgrading `tzdata` resolved the bug for me also.
> 
> I installed downgrade with yay `yay -S downgrade`. Then I run `sudo downgrade tzdata`, and I selected 2024a-2. After that I restart it with `pkill waybar & waybar &`.
> 
> Hope this bug will be fixed

Downgrading did help in my case. *Thank you!*
But, is the bug related to `tzdata` **2024b** or `waybar`?

**Comment by sgse** [comment]
`[warning] Timezone: Europe/Berlin. std::chrono::tzdb: cannot locate zone: Europe/Berlin`

It is related to tzdata

**Comment by Loara** [comment]
On Arch Linux if I try to list all the timezones contained in `tzdb`
```
#include <chrono>
#include <iostream>

int main() {
    const std::vector<std::chrono::time_zone> &zones = std::chrono::get_tzdb().zones;
    for(const std::chrono::time_zone &i : zones) {
        std::cout << i.name() << std::endl;
    }
}
```
then I get only the following timezones
```
Etc/GMT
Etc/UTC
```
and this is the reason tzdb doesn't recognize any other timezone.

## Links:
[https://en.cppreference.com/w/cpp/chrono/tzdb](https://en.cppreference.com/w/cpp/chrono/tzdb)

**Comment by itaranto** [comment]
Guys I think we could be misleading the devs here, as far as I understand there's 2 issues here:

- The original issue about the timezone not being detected automatically since v.0.10
- A recent issue related to `tzdata` that prevents you to have a local timezone even when set manually.

I think this should be split into two different issues.

**Comment by enabwds** [comment]
Agreed

**Comment by luffyxxsenpai** [comment]
another one confirming downgrading tzdata 2024a-1 or 2024a-2 fix the issue


i literally messed up my hwclock timedatectl bios clock everything lol

![image](https://github.com/user-attachments/assets/b9cfdd19-b386-4588-8fc6-0b66ba1f529e)

**Comment by YiitWT** [comment]
About to kms if clock keeps showing wrong in waybar

**Comment by KorigamiK** [comment]
> About to kms if clock keeps showing wrong in waybar

replace the clock module with something similar int the meantime:
```json
  "custom/clock": {
    "exec": "date +\"%I:%M %p\"",
    "format": " {}",
    "interval": 10
  },
```

**Comment by Nj0be** [comment]
Unfortunately tzdata 2024b-2 (now in core-testing for archlinux) doesn't solve the issue...

**Comment by skinnypuppy** [comment]
Just installed vanilla arch, the issue appears to be fixed as my clock in the waybar is correct. Tzdata version is 2024b-2 from core-testing.

**Comment by Tosainu** [comment]
It looks like the recent  `tzdata` issue has been solved by `gcc-14.2.1+r134+gab884fffe3fc-1`.

https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/commit/2d0f36bcac02e8ebe25f3c187c51285bd1741737

**Comment by Kommynct** [comment]
However, the issue in the post is still present, and is unrelated to tzdata, I believe you all are looking for issue https://github.com/Alexays/Waybar/issues/3575

**Comment by beeender** [comment]
> It looks like the recent `tzdata` issue has been solved by `gcc-14.2.1+r134+gab884fffe3fc-1`.
> 
> https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/commit/2d0f36bcac02e8ebe25f3c187c51285bd1741737

Re-building waybar with the latest GCC fixes the issue.

**Comment by mprelec** [comment]
Thanks for the update on the issue. 
Update to latest gcc-libs and gcc fixed it on my arch.
Then just do a 
_pkill waybar && waybar -c /path/to/waybar_config -s /path/to/waybar_style.css &_
Cheers

**Comment by gammons** [comment]
Fix confirmed.  Just doing a regular `pacman -Syu` pulled in the update to `gcc-libs` and `gcc`, and once that completed I ran waybar again, and the timezone issue was fixed. :tada:

**Comment by cold-bin** [comment]
thanks.

**Comment by itaranto** [comment]
> However, the issue in the post is still present, and is unrelated to tzdata, I believe you all are looking for issue #3575

Yes, this issue still happens to me (it's not related with `tzdata` at all).

**Comment by itaranto** [comment]
@Kommynct I'd suggest closing this issue and creating a new one, otherwise it will be _very_ confusing for the devs.

**Comment by Kommynct** [comment]
i suggest people powt about their issue in the relevant issue trackers instead of taking over an unrelated one

**Comment by itaranto** [comment]
> i suggest people post about their issue in the relevant issue trackers instead of taking over an unrelated one

Yes, I was about to say your issue got hi-jacked by another one :man_shrugging:

**Comment by WhyNotHugo** [comment]
This ticket is about an issue that has been around since March.

For a similar issue that appeared about two weeks ago, see https://github.com/Alexays/Waybar/issues/3655

**Comment by colemickens** [comment]
```
❯ timedatectl
               Local time: Sun 2024-12-08 19:10:26 -03
           Universal time: Sun 2024-12-08 22:10:26 UTC
                 RTC time: Sun 2024-12-08 22:10:26
                Time zone: America/Argentina/Buenos_Aires (-03, -0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

My Waybar **incorrectly** says the titme is 22:10, which is quite clearly wrong.

**Comment by lukacerr** [comment]
Seems like an Argentinian issue at this point lol
Sum myself to the rest
```
❯ timedatectl
               Local time: Mon 2024-12-09 19:37:54 -03
           Universal time: Mon 2024-12-09 22:37:54 UTC
                 RTC time: Mon 2024-12-09 19:37:53
                Time zone: America/Argentina/Buenos_Aires (-03, -0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: yes
```

Fresh install, SUSE Tumbleweed.

**Comment by Kommynct** [comment]
i'm not in argentina, definitely not an argentinian issue.

**Comment by Pablo1107** [comment]
> i'm not in argentina, definitely not an argentinian issue.

That would be oddly specific.

**Comment by WhyNotHugo** [comment]
The issue went away for me eventually.

These seem to be two different causes for this issue. AFAIK, one of them was a bug in the c++ stdlib.

**Comment by colemickens** [comment]
I travel constantly and have no desire or intention to constantly reset my waybar config for a timezone. That's uh, why I update my system's local timezone.

So does anyone understand what the actual issue is? Downgrading tzdata is not something I'm interested in doing. Nor is C++. But more than my disdain for C++ is my desire for my clock to report the correct time. It's massively confusing and sometimes detrimental for Waybar to just.... be showing the completely wrong time.

Also, I'm a bit shocked that this isn't even more widely noticed. Are the users not in this thread rocking distros with really out of date tzdata, or what?

**Comment by alexlnkp** [comment]
> I travel constantly and have no desire or intention to constantly reset my waybar config for a timezone. That's uh, why I update my system's local timezone.
> 
> So does anyone understand what the actual issue is? Downgrading tzdata is not something I'm interested in doing. Nor is C++. But more than my disdain for C++ is my desire for my clock to report the correct time. It's massively confusing and sometimes detrimental for Waybar to just.... be showing the completely wrong time.
> 
> Also, I'm a bit shocked that this isn't even more widely noticed. Are the users not in this thread rocking distros with really out of date tzdata, or what?

As far as i understand, the issue was really glibc, which got rebuilt against newest tzdata (which wasn't in the upstream yet) and this way it broke some apps.
I'm not experiencing any issues at the moment on arch linux, though

**Comment by colemickens** [comment]
Downgrading tzdata is not an option for me. I struggle to believe that current, stable glibc + tzdata are so badly broken for 6 months that there isn't a bug in Waybar.

**Comment by colemickens** [comment]
Maybe this is related. My system thinks that the clock is UTC time, but it seems like it's not actually:

```
❯ timedatectl
               Local time: Fri 2024-12-13 10:37:47 -03
           Universal time: Fri 2024-12-13 13:37:47 UTC
                 RTC time: Fri 2024-12-13 13:37:47
                Time zone: America/Argentina/Buenos_Aires (-03, -0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

❯ sudo !!
sudo hwclock
2024-12-13 10:38:11.163333-03:00

~
❯ sudo hwclock --utc
2024-12-13 10:38:52.213120-03:00

~
❯ sudo hwclock --localtime
2024-12-13 13:39:05.157181-03:00
```

I'm sort of out of my depth here.

**Comment by itaranto** [comment]
> ~Maybe this is related. My system thinks that the hwclock is UTC time, but it seems like it's not actually:~
> 
> ```
> ❯ timedatectl
>                Local time: Fri 2024-12-13 10:37:47 -03
>            Universal time: Fri 2024-12-13 13:37:47 UTC
>                  RTC time: Fri 2024-12-13 13:37:47
>                 Time zone: America/Argentina/Buenos_Aires (-03, -0300)
> System clock synchronized: yes
>               NTP service: active
>           RTC in local TZ: no
> 
> ❯ sudo !!
> sudo hwclock
> 2024-12-13 10:38:11.163333-03:00
> 
> ~
> ❯ sudo hwclock --utc
> 2024-12-13 10:38:52.213120-03:00
> 
> ~
> ❯ sudo hwclock --localtime
> 2024-12-13 13:39:05.157181-03:00
> ```
> 
> **waybar shows 13:39**
> 
> ~I'm sort of out of my depth here, but I suspect this is related.~
> 
> Reading `sudo hwclock --debug` output indicates this is all as expected. I'm quite sure this is a bug in Waybar. This issue does not affect any other desktop, any other application, any other anything on my system. Only Waybar.

I have a similar output on Arch Linux:

```
$ timedatectl
               Local time: Sat 2024-12-14 09:52:08 -03
           Universal time: Sat 2024-12-14 12:52:08 UTC
                 RTC time: Sat 2024-12-14 12:52:07
                Time zone: America/Argentina/Cordoba (-03, -0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
          
$ sudo hwclock
2024-12-14 09:52:46.393252-03:00
```

Waybar displays 12:52.

**Comment by rnb42** [comment]
I have the same issue on Voidlinux with up-to-date packages
Waybar displayed UTC instead of CET(UTC+1)
I followed the advice from the other issue and downgraded the tzdata package from 2025a to 2024a(using xdowngrade in /var/cache/xbps) and now it shows the correct time again.

**Comment by ianhein** [comment]
> Issue still remains with `Waybar v0.10.2`. Workaround is manually set the timezone in `~/.config/waybar/config`:
> 
> ```
>     "clock#date": {
>         "timezone": "America/Argentina/Buenos_Aires",
>         "format": "{:%A %b %d}",
>         "format-alt": "{:%Y-%m-%d}",
>         "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
>         "interval": 60
>     },
>     "clock#time": {
>         "timezone": "America/Argentina/Buenos_Aires",
>         "format": "{:%H:%M:%S}",
>         "interval": 1
>     },
> ```

This fixed it. I'm also in Argentina lol

**Comment by khaled4vokalz** [comment]
any fix for this? This is happening for me as well :(

**Comment by khaled4vokalz** [comment]
installing https://archive.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata_2024b-1ubuntu2.2_all.deb fixed it for me

**Comment by noahrama** [comment]
`
$ waybar --version
Waybar v0.11.0

$ timedatectl
               Local time: Mon 2025-03-03 17:43:19 AEDT
           Universal time: Mon 2025-03-03 06:43:19 UTC
                 RTC time: Mon 2025-03-03 06:43:19
                Time zone: Australia/Sydney (AEDT, +1100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

$ date
Mon 03 Mar 2025 17:43:21 AEDT
`

Waybar is still not respecting localtime

**Comment by gmoque** [comment]
> Downgrading tzdata is not an option for me. I struggle to believe that current, stable glibc + tzdata are so badly broken for 6 months that there isn't a bug in Waybar.

Here's the tracking issue for the broken TZ implementation: https://github.com/Alexays/Waybar/issues/3575.

**Comment by Kommynct** [comment]
Does anybody have a workaround for this? it has been over a year, surely somebody has worked out something?

**Comment by MartinCura** [comment]
🇦🇷 World champions (in broken clocks). Thanks for the workaround, it's fine for me, hope somebody finds the actual problem/solution.

**Comment by rossabaker** [comment]
My waybar (0.14.0, gcc-15.2.0, NixOS) runs in UTC when /etc/localtime points to a zone with three segments:

```console
$ readlink /etc/localtime 
zoneinfo/America/Indiana/Indianapolis
```

It shows my local time if I use a legacy zone name with two segments:

```console
$ readlink /etc/localtime 
zoneinfo/America/Indianapolis
```

It also shows my local time if I create /etc/timezone with the canonical zone name, regardless of how /etc/localtime is set:

```console
$ cat /etc/timezone 
America/Indiana/Indianapolis
```

I believe the cause is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=122567.

**Comment by 7sev7nsev7n7** [comment]
> My waybar (0.14.0, gcc-15.2.0, NixOS) runs in UTC when /etc/localtime points to a zone with three segments:
> 
> $ readlink /etc/localtime 
> zoneinfo/America/Indiana/Indianapolis
> 
> It shows my local time if I use a legacy zone name with two segments:
> 
> $ readlink /etc/localtime 
> zoneinfo/America/Indianapolis
> 
> It also shows my local time if I create /etc/timezone with the canonical zone name, regardless of how /etc/localtime is set:
> 
> $ cat /etc/timezone 
> America/Indiana/Indianapolis
> 
> I believe the cause is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=122567.

i might just not be knowledgeable but why do your links not include `/usr/share` in them?

ETA: for example, the output in my case is

```
[I] 7sev7nsev7n7@mirthe ~ $ readlink /etc/localtime
/usr/share/zoneinfo/Mexico/General
[I] 7sev7nsev7n7@mirthe ~ $ file $(!!)
file $(readlink /etc/localtime)
/usr/share/zoneinfo/Mexico/General: timezone data (fat), version 2, 8 gmt time flags, 8 std time flags, no leap seconds, 68 transition times, 8 local time types, 24 abbreviation chars
[I] 7sev7nsev7n7@mirthe ~ $ 
```

**Comment by rossabaker** [comment]
Mine is a relative link.  I'm on NixOS, which doesn't have a /usr/share.  If I follow all the links, it goes to the Nix store:

```console
$ readlink /etc/localtime
zoneinfo/America/Indianapolis

$ readlink -f /etc/localtime
/nix/store/r29gp232igs3m47s7lfcaalfashd82bf-tzdata-2025c/share/zoneinfo/America/Indianapolis
```

The real problem is the GCC library.  No matter where the zoneinfo actually lives, it only tries two path segments before falling through to the next source.

**Comment by Alexays** [comment]
Status update, since this thread has accumulated a few distinct root causes over the years and it's worth untangling what's actually fixed vs. what remains:

**Fixed / resolved**

- The **tzdata 2024b episode** (Sept 2024, a flood of `std::chrono::tzdb: cannot locate zone` warnings and everything falling back to UTC) was an `gcc-libs`/libstdc++ regression, not Waybar. It was resolved upstream by the `gcc-libs` 14.2.1 rebuild — a normal `pacman -Syu` (or distro equivalent) fixes it, no downgrade needed.
- A separate **clock/calendar tooltip crash around DST transitions** was fixed on git master (commit d130ce6a, part of #5158) by disambiguating the ambiguous fall-back hour with `choose::earliest`.

**Still outstanding (upstream, not fixable in Waybar)**

The remaining "shows UTC instead of local time" reports — very common for **three-segment canonical zone names** like `America/Argentina/Buenos_Aires` and `America/Indiana/Indianapolis` (thanks @rossabaker for pinning this down) — are an upstream libstdc++ bug: [GCC #122567](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=122567). `std::chrono::current_zone()` only walks two path segments of `/etc/localtime` before falling through to UTC, so any zone with three segments is misdetected. Waybar just calls `current_zone()` here, so there's nothing we can correct on our side until the libstdc++ fix lands.

**Workarounds until then** (any one works):
- Set the zone explicitly: `"timezone": "America/Argentina/Buenos_Aires"`
- Export `TZ` before launching Waybar — our `local_zone()` honors `$TZ` first
- Create `/etc/timezone` with the canonical name
- Use the legacy 2-segment alias (e.g. `America/Indianapolis`)

Keeping this open to track the upstream GCC fix. 🙏

**Comment by Alexays** [comment]
Closing — the Waybar-side parts (the DST-hour clock crash, the tzdata flood) are fixed/resolved; the remaining wrong-zone display for three-segment zones is an upstream libstdc++/GCC bug (GCC #122567, see above) that Waybar can't work around (it just calls current_zone()). Reopen if you're seeing a wrong zone that isn't that upstream case. 🙏
