### ISSUE TITLE
Hyprland plugin broken due to new socket location

### ISSUE THREAD

**Issue by CelestialCrafter** [Alexays/Waybar#3209]
Hyprland recently changed their socket location from /tmp/hypr to $XDG_RUNTIME_DIR/hypr, so waybar now breaks when trying to connect to the Hyprland socket.

example:
```
[2024-05-04 17:43:47.784] [info] Using configuration file /home/celestial/.config/waybar/config.jsonc
[2024-05-04 17:43:47.785] [info] Using CSS file /home/celestial/.config/waybar/style.css
[2024-05-04 17:43:47.791] [info] Hyprland IPC starting
[2024-05-04 17:43:47.791] [error] Hyprland IPC: Unable to connect?
[2024-05-04 17:43:47.791] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/a3309b51a254f142c535022615be6f76eb23fa9b_1714862139_15392527/.socket.sock. (3)
[2024-05-04 17:43:47.791] [warning] module hyprland/workspaces: Disabling module "hyprland/workspaces", Error parsing JSON: * Line 1, Column 1
  Syntax error: value, object or array expected.
[2024-05-04 17:43:47.922] [info] Bar configured (width: 1920, height: 41) for output: DP-4
```

![image](https://github.com/Alexays/Waybar/assets/44733683/ec648768-a9b5-4c7f-91ce-49b1085e9f89)
![image](https://github.com/Alexays/Waybar/assets/44733683/afae5c94-300b-49cf-9eca-81ffdc1e1b7f)

Hyprland commit a3309b51a254f142c535022615be6f76eb23fa9b

Waybar version 0.9.24

**Comment by CelestialCrafter** [comment]
found out this is already fixed, sorry!

**Comment by CelestialCrafter** [comment]
works for me, did you `nix flake update`?

**Comment by shot-codes** [comment]
@CelestialCrafter I still have the same issue. You can see my setup here https://github.com/shot-codes/nix, https://github.com/shot-codes/nix/blob/main/home/waybar.nix
