### ISSUE TITLE
Custom module has no rendered text/icon

### ISSUE THREAD

**Issue by A** [Alexays/Waybar#3782]
If i use `"format": "{icon}"` icon is rendered correctly, if I use `"format": "{}"` text is rendered correctly, if i use `"format": "{} {icon}"` text and icon is rendered correctly, but if I use `"format": "{icon} {}"` module is still clickable, but renders and empty string.

Waybar v0.11.0

Configuration:

```
  "custom/notification": {
    "tooltip": false,
    "format": "{icon} {}",
    "format-icons": {
      "notification": "<span foreground='#f38080'><sup></sup></span>",
      "none": "",
      "dnd-notification": "<span foreground='#f38080'><sup></sup></span>",
      "dnd-none": "",
      "inhibited-notification": "<span foreground='#f38080'><sup></sup></span>",
      "inhibited-none": "",
      "dnd-inhibited-notification": "<span foreground='#f38080'><sup></sup></span>",
      "dnd-inhibited-none": ""
    },
    "return-type": "json",
    "exec-if": "which swaync-client",
    "exec": "swaync-client -swb",
    "on-click": "swaync-client -t -sw",
    "on-click-right": "swaync-client -d -sw",
    "escape": true
  },
```

`swaync-client -swb` output:

```
{"text": "237", "alt": "dnd-notification", "tooltip": "237 Notifications", "class": "dnd-notification"}   
```

**Comment by alterNERDtive** [comment]
I am experiencing the same issue; it is not limited to `custom` modules. It applies to any module, but most actual modules come with identifiers instead of the default `{}` (and those work fine).

**Comment by A** [comment]
I think this one was addressed in  `a3e7031`, but hasn't been published yet. Works for me via `waybar-git`.

**Comment by alterNERDtive** [comment]
I am still having this issue with a similar configuration to the original issue. Using `{text}` instead of `{}` works 🤷🏿

`waybar-0.12.0-2.fc42.x86_64` on Fedora 42. The relevant part of the config is

```
  "custom/notification": {
    "format": "{icon} {}</span>",
    "tooltip": false,
    "format-icons": {
      "notification": "<span foreground='red'>",
      "none": "<span foreground='#fdf6e3'>",
      "dnd-notification": "<span>",
      "dnd-none": "<span>",
      "inhibited-notification": "<span foreground='red'>",
      "inhibited-none": "<span foreground='#fdf6e3'>",
      "dnd-inhibited-notification": "<span>",
      "dnd-inhibited-none": "<span>"
    },
    "return-type": "json",
    "exec-if": "which swaync-client",
    "exec": "swaync-client -swb",
    "on-click": "swaync-client -t -sw",
    "on-click-right": "swaync-client -d -sw",
    "escape": true
  },
```
