### ISSUE TITLE
waybar stops talking to hyprland ipc after a display is plugged in/out

### ISSUE THREAD

**Issue by gottaeat** [Alexays/Waybar#3975]
```
$ Hyprland --version
Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.2
```

```
$ waybar --version
Waybar v0.12.0
```

`config.jsonc`:
```
{
    "layer": "top",
    "position": "top",
    "height": "",
    "width": "",
    "spacing": 4,
    "modules-left": [
        "hyprland/workspaces"
    ],
    "modules-right": [
        "hyprland/language",
        "tray"
    ],
    "hyprland/language": {
        "format": "{short}"
    },
    "tray": {
        "icon-size": 21,
        "spacing": 1
    }
}
```

hyprland display config:
```
monitor = DP-1, 3840x2160@60, 0x0, 1.5, bitdepth, 8
monitor = HDMI-A-1, 1920x1080@60, 2560x0, 1, bitdepth, 8, vrr, 0
```

full process log:
```
[2025-03-08 15:09:48.443] [info] Using configuration file /home/user/.config/waybar/config.jsonc
[2025-03-08 15:09:48.445] [info] Discovered appearance 'dark'
[2025-03-08 15:09:48.445] [info] Using CSS file /home/user/.config/waybar/style.css
[2025-03-08 15:09:48.447] [info] Hyprland IPC starting
[2025-03-08 15:09:48.447] [info] Loading persistent workspaces from Hyprland workspace rules
[2025-03-08 15:09:48.476] [info] Loading persistent workspaces from Hyprland workspace rules
[2025-03-08 15:09:48.513] [info] Bar configured (width: 2560, height: 24) for output: DP-1
[2025-03-08 15:09:48.513] [info] Bar configured (width: 1920, height: 24) for output: HDMI-A-1
[2025-03-08 15:09:48.519] [info] Bar configured (width: 1920, height: 24) for output: HDMI-A-1

# - - HDMI-A-1 DISCONNECTED HERE - - #

# - - HDMI-A-1 PLUGGED BACK IN - - #

** (waybar:32723): CRITICAL **: 15:10:06.567: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.567] [info] Hyprland IPC stopping...

** (waybar:32724): CRITICAL **: 15:10:06.568: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.568] [info] Hyprland IPC stopping...

** (waybar:32725): CRITICAL **: 15:10:06.569: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.569] [info] Hyprland IPC stopping...

** (waybar:32726): CRITICAL **: 15:10:06.569: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.570] [info] Hyprland IPC stopping...

** (waybar:32733): CRITICAL **: 15:10:06.571: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.571] [info] Hyprland IPC stopping...

** (waybar:32734): CRITICAL **: 15:10:06.571: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.571] [info] Hyprland IPC stopping...

** (waybar:32735): CRITICAL **: 15:10:06.572: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.572] [info] Hyprland IPC stopping...

** (waybar:32736): CRITICAL **: 15:10:06.573: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.573] [info] Hyprland IPC stopping...

** (waybar:32737): CRITICAL **: 15:10:06.574: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-08 15:10:06.574] [info] Hyprland IPC stopping...
[2025-03-08 15:10:06.575] [info] Bar removed from output: HDMI-A-1
[2025-03-08 15:10:07.179] [info] Loading persistent workspaces from Hyprland workspace rules
[2025-03-08 15:10:07.202] [info] Bar configured (width: 1920, height: 24) for output: HDMI-A-1
[2025-03-08 15:10:07.205] [info] Bar configured (width: 1920, height: 24) for output: HDMI-A-1
```
after the last logline none of the `hyprland/*` modules work in any of the outputs.

**Comment by ctilley83** [comment]
I have a similar issue, but the trigger is when hypridle turns on the display after idle. It seems waybar is looking for the display before it has time to fully wake.

**Comment by 123Daktary** [comment]
Hello! I'm also having a similar issue as OP but I'm facing this issue when I'm manually disabling my laptop's monitor.

Steps to reproduce:
1. A multi-monitor setup is needed. Start with one monitor disabled and without waybar running as a background process
2. Run "waybar" in a terminal window
3. In a new terminal window, enable the monitor via Hyprland command
4. Disable the monitor via Hyprland command

Issue:
After a monitor is disabled, waybar doesn't refresh the "hyprland/workspaces" and "hyprland/window" modules anymore for the active monitor. All other modules seem to work fine, like "clock", "tray", "pulseaudio", etc.

Outputs:

- Step 2

Terminal 1

```
$ waybar
[2025-03-11 17:18:58.771] [info] Using configuration file /home/<user>/.config/waybar/config.jsonc
[2025-03-11 17:18:58.774] [info] Using CSS file /home/<user>/.config/waybar/style.css
[2025-03-11 17:18:58.781] [info] Hyprland IPC starting
[2025-03-11 17:18:58.782] [info] Loading persistent workspaces from Hyprland workspace rules
[2025-03-11 17:18:58.942] [info] Bar configured (width: 1920, height: 25) for output: HDMI-A-1
[2025-03-11 17:18:58.942] [error] Item '': No icon name or pixmap given.
```

- Step 3

Terminal 2
```
$ hyprctl keyword monitor "eDP-1, 1920x1080, -1920x0, 1"
```

Terminal 1
```
[2025-03-11 17:19:12.847] [info] Loading persistent workspaces from Hyprland workspace rules
[2025-03-11 17:19:12.973] [info] Bar configured (width: 1920, height: 25) for output: eDP-1
[2025-03-11 17:19:12.973] [error] Item '': No icon name or pixmap given.
```

- Step 4

Terminal 2
```
hyprctl keyword monitor "eDP-1, disable"
```

Terminal 1
```

** (waybar:16540): CRITICAL **: 17:46:05.034: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-11 17:46:05.034] [info] Hyprland IPC stopping...

** (waybar:16542): CRITICAL **: 17:46:05.039: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-03-11 17:46:05.040] [info] Hyprland IPC stopping...
[2025-03-11 17:46:05.044] [info] Bar removed from output: eDP-1
```

This is when the Hyprland modules start freezing. To recover, I have a script associated to a hotkey that restarts waybar.

Running on Arch with Waybar v0.12.0 and latest stable release of Hyprland.

Hope this helps in tracking down the bug!

**Comment by auroraveon** [comment]
it also happens to me when i have i have sigusr2 to waybar a few times to reload my theme qwq

**Comment by dybdeskarphet** [comment]
I'm having the same problem too. Other modules just work fine but hyprland module freezes after a display is plugged in or out.

**Comment by winkelnp** [comment]
> Steps to reproduce:
> 
>     1. A multi-monitor setup is needed. Start with one monitor disabled and without waybar running as a background process
> 
>     2. Run "waybar" in a terminal window
> 
>     3. In a new terminal window, enable the monitor via Hyprland command
> 
>     4. Disable the monitor via Hyprland command

On my end it also occurs if the monitor is already running and is only disabled while waybar is running, i.e.:
1. A multi-monitor setup is needed, start with normal configuration and without waybar as background process
2. run "waybar" in a terminal window
3. Disable one of the monitors via Hyprland command

This gives the following output:
```
** (waybar:916248): CRITICAL **: 12:35:02.150: static void Glib::DispatchNotifier::unreference_instance(Glib::DispatchNotifier*, const Glib::Dispatcher*): assertion 'instance == notifier' failed
[2025-04-12 12:35:02.150] [info] Hyprland IPC stopping...
[2025-04-12 12:35:02.151] [info] Bar removed from output: eDP-1
```

Adding a monitor does not seem to cause this, only removing (whether or not that monitor was already enabled when waybar starts)

**Comment by dybdeskarphet** [comment]
Hey, here is a quick fix for you guys until this issue is solved:

```bash
#!/bin/bash

waybar &

handle() {
  case "$1" in
  monitoraddedv2* | monitorremovedv2*)
    killall waybar
    sleep 0.3
    waybar &
    ;;
  esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
```

Start this script instead of using the `waybar` command and it will restart the bar when a display is plugged in/out. And because it uses the socket directly, there is no polling.

**Comment by lfos** [comment]
Looks like this may be a regression caused by #3945, hopefully the original PR author has sufficient context to take a look and come up with a quick fix.

**Comment by zjeffer** [comment]
I'll have a look soon, thanks for the ping.

I've been having the same issue for a while (I have a keybind to restart waybar similar to @dybdeskarphet's solution) , wasn't aware that it's my PR that might be causing this 😆

**Comment by zjeffer** [comment]
Reading the thread more thoroughly now, it's not the same issue I was experiencing. In my case, disconnecting my laptop from my docking station (which has 2 monitors connected) sometimes crashes waybar, but it's quite rare.

I tried to reproduce this issue using @123Daktary and @winkelnp's steps but couldn't reproduce it. Can someone turn on trace logging (`--log-level trace`) when starting waybar, and post the trace logs after reproducing it? Also include your Hyprland and Waybar versions, and how often you can reproduce it (every time, only once in x times, etc). Thanks.

I'll have another look at the IPC code in the meantime.

**Comment by lfos** [comment]
> I tried to reproduce this issue using [@123Daktary](https://github.com/123Daktary) and [@winkelnp](https://github.com/winkelnp)'s steps but couldn't reproduce it. Can someone turn on trace logging (`--log-level trace`) when starting waybar, and post the trace logs after reproducing it? Also include your Hyprland and Waybar versions, and how often you can reproduce it (every time, only once in x times, etc). Thanks.

Thanks for taking a look!

I followed these steps:

1. Have the following bindings in my hyprland config to automatically enable/disable the laptop monitor when I open/close the lid:
    ```
    bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1,disable"
    bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1,3072x1920@120.00Hz,0x0,1.5"
    ```
2. Run hyprland and waybar on external monitor. Switch workspaces - all good.
3. Open laptop lid; brings up the additional laptop monitor. Switch workspaces - all good.
4. Close laptop lid again; disables the additional laptop monitor. Switch workspaces - active workspace doesn't seem to get updated on waybar anymore.

Trace log excerpt: https://gist.githubusercontent.com/lfos/529fa170344e39eab7e1dd620edf608d/raw

Let me know if you need anything else!

**Comment by zjeffer** [comment]
I tried reproducing it the same way but even after turning the display off and on 5 times in a row, everything still works fine.

Can you run waybar with gdb (preferably built from source so you have debug symbols), reproduce the issue, then when it freezes, send a SIGINT and post the full backtrace?

**Comment by lfos** [comment]
> Can you run waybar with gdb (preferably built from source so you have debug symbols), reproduce the issue, then when it freezes, send a SIGINT and post the full backtrace?

Not on my machine right now, but for clarity -- waybar itself does not freeze -- it just disconnects from hyprland IPC (also see trace log above). All other waybar modules still work perfectly fine.

**Comment by zjeffer** [comment]
I'm guessing the IPC mutex is being deadlocked, I'll try to investigate with thread sanitizer.

**Comment by zjeffer** [comment]
Thread sanitizer found one issue which I fixed here: https://github.com/Alexays/Waybar/pull/4359

Can you test whether you can reproduce the issue with that PR?

**Comment by lfos** [comment]
Thanks for the patch. That doesn't fix it unfortunately.

That said, in my latest round of tests, I had to repeat the steps 5-10 times to reproduce. This may or may not be related to your patch.

I also noticed that my earlier statement (as well as the original bug report) are somewhat incorrect/misleading; based on the trace log, the hyprland waybar module still receives all IPC messages, including workspace changes and active window changes. (But the hyprland section in the widget doesn't get updated.)

**Comment by lfos** [comment]
The assumption that the issue is caused by IPC communication breaking down was probably due to `Hyprland IPC stopping...` appearing in the logs, but that may be a red herring. @zjeffer - Do you know if that message is expected/harmless when a monitor is disabled?

**Comment by lfos** [comment]
@zjeffer - I also noticed your PR is based on a quite old commit that may predate the code introducing the issue; are you running your tests with current HEAD?

**Comment by zjeffer** [comment]
Nice catch, I wasn't. I now rebased it on latest master.

**Comment by zjeffer** [comment]
> The assumption that the issue is caused by IPC communication breaking down was probably due to Hyprland IPC stopping... appearing in the logs, but that may be a red herring. @zjeffer - Do you know if that message is expected/harmless when a monitor is disabled?

The Hyprland IPC in Waybar is a singleton that is shared across all waybar instances, it should only stop once waybar itself terminates. So it's very strange that you guys are seeing that log multiple times in a row...

EDIT: at least, the OP's description shows this. Your trace log only shows it once, then after that you keep receiving IPC events.

**Comment by lfos** [comment]
> The Hyprland IPC in Waybar is a singleton that is shared across all waybar instances, it should only stop once waybar itself terminates. So it's very strange that you guys are seeing that log multiple times in a row...

Are you able to reproduce the issue after upgrading to current HEAD? Is there anything else we can do to help troubleshoot?

**Comment by zjeffer** [comment]
At the start of your log, you have this:
```
[2025-08-10 14:14:33.581] [info] Hyprland IPC starting
[2025-08-10 14:14:33.581] [debug] window-rewrite is not defined or is not an object, using default rules.
[2025-08-10 14:14:33.581] [info] Hyprland IPC starting
```
Are you starting multiple instances of Waybar?

**Comment by zjeffer** [comment]
> Are you able to reproduce the issue after upgrading to current HEAD? Is there anything else we can do to help troubleshoot?

Still can't reproduce, neither on latest master nor on my branch.

Can you reproduce it with a very minimal config? For example only the hyprland/workspaces module with no options.

**Comment by lfos** [comment]
The duplicate message appears to be due to having both `hyprland/windowcount` and `hyprland/workspaces` modules in use. If I remove `hyprland/windowcount`, one of the messages disappears.

Good idea to try with a minimal config. I wasn't able to reproduce with this one:
```
{
    "output": ["eDP-1", "DP-1"],
    "modules-left": ["hyprland/workspaces"],
},
```

Now trying to reintroduce things until the issue reappears.

**Comment by zjeffer** [comment]
Ah, that explains it. 
Probably caused by this PR: https://github.com/Alexays/Waybar/pull/4219 which creates another instance of the IPC. I'll do some testing

I can't reproduce it with hyprland/windowcount, but I'll fix the double IPC creation anyway.

**Comment by lfos** [comment]
Another interesting observation, likely related to the last three comments: `hyprland/windowcount` continues to work fine when the issue is triggered, while `hyprland/workspaces` and `hyprland/window` both stop working.

That said, it turns out to be difficult to figure out what exactly in the config is causing the issue. It doesn't seem to be triggered with small configs and seems to be triggered with more complex configs -- but I couldn't identify any single change that seems to cause it. Maybe that's simply due to the issue being non-deterministic and higher complexity increasing the odds of the issue appearing.

I'll now try to revert commit 2b9601b9 (added IPC fix and Nix GPS fix, 2025-06-22) locally and test. Thanks for the pointer.

**Comment by lfos** [comment]
I wasn't able to revert commit https://github.com/Alexays/Waybar/commit/2b9601b9a44092b740448ee691a923573f1597ed (added IPC fix and Nix GPS fix, 2025-06-22), as it resulted in a build error.

However, after I modified the `hyprland/windowcount` module to use shared IPC (see https://gist.githubusercontent.com/lfos/b63d6a7999ff84cec3b8e53d821ebcc1/raw), the `hyprland/windowcount` module now also freezes whenever the issue is triggered.

It looks like there clearly is an issue with the shared IPC implementation in hyprland modules.

**Comment by zjeffer** [comment]
Can you post your waybar config?

**Comment by lfos** [comment]
> Can you post your waybar config?

My waybar config has a lot of custom scripts that won't run as-is on a different system. Unfortunately, I can't seem to reproduce the bug when I remove those custom modules. I can try to build a mock config to reproduce but it'll take some time.

**Comment by lfos** [comment]
In the meantime, I'm using the following workaround, which seems to fix the issue:

```diff
diff --git a/include/modules/hyprland/backend.hpp b/include/modules/hyprland/backend.hpp
index d9f16526..ca986c62 100644
--- a/include/modules/hyprland/backend.hpp
+++ b/include/modules/hyprland/backend.hpp
@@ -20,7 +20,6 @@ class EventHandler {
 class IPC {
  public:
   IPC();
-  ~IPC();
   static IPC& inst();
 
   void registerForIPC(const std::string& ev, EventHandler* ev_handler);
diff --git a/src/modules/hyprland/backend.cpp b/src/modules/hyprland/backend.cpp
index 2bd3b509..92c4f070 100644
--- a/src/modules/hyprland/backend.cpp
+++ b/src/modules/hyprland/backend.cpp
@@ -48,22 +48,6 @@ IPC::IPC() {
   ipcThread_ = std::thread([this]() { socketListener(); });
 }
 
-IPC::~IPC() {
-  running_ = false;
-  spdlog::info("Hyprland IPC stopping...");
-  if (socketfd_ != -1) {
-    spdlog::trace("Shutting down socket");
-    if (shutdown(socketfd_, SHUT_RDWR) == -1) {
-      spdlog::error("Hyprland IPC: Couldn't shutdown socket");
-    }
-    spdlog::trace("Closing socket");
-    if (close(socketfd_) == -1) {
-      spdlog::error("Hyprland IPC: Couldn't close socket");
-    }
-  }
-  ipcThread_.join();
-}
-
 IPC& IPC::inst() {
   static IPC ipc;
   return ipc;
```

I don't fully understand why the destructor of the static IPC is sometimes called while the program continues running. Maybe an edge case during exception handling?

**Comment by zjeffer** [comment]
> I don't fully understand why the destructor of the static IPC is sometimes called while the program continues running. Maybe an edge case during exception handling?

Does this also happen on [this PR's branch]( https://github.com/Alexays/Waybar/pull/4359)?

**Comment by lfos** [comment]
> > I don't fully understand why the destructor of the static IPC is sometimes called while the program continues running. Maybe an edge case during exception handling?
> 
> Does this also happen on [this PR's branch](https://github.com/Alexays/Waybar/pull/4359)?

It does, and gets a little worse, as now the `hyprland/windowcount` module is impacted too.

**Comment by lfos** [comment]
@zjeffer - Do you have any idea what could trigger the static IPC destructor while waybar continues execution?

**Comment by zjeffer** [comment]
> Do you have any idea what could trigger the static IPC destructor while waybar continues execution?

That should only happen if the hyprland modules themselves are destructed, while the rest of waybar keeps running. No idea how that can happen. 

Sadly as long as I can't reproduce this myself, I don't know how to proceed...

**Comment by lfos** [comment]
I finally have a minimal config to reproduce:

```
{
    "output": ["eDP-1", "DP-1"],
    "modules-left": ["hyprland/workspaces"],
    "modules-right": ["custom/worker", "custom/worker", "custom/worker", "custom/worker", "custom/worker"],
    "custom/worker": {
        "format": "{}",
        "restart-interval": 30,
        "return-type": "json",
        "exec": "~/.config/waybar/modules/worker.sh",
    },
}
```

... where `~/.config/waybar/modules/worker.sh` is a simple bash script:
```bash
#!/bin/bash

while true; do
	echo "{\"text\":\"Test\"}"
	sleep 60
done
```

Note that having just one custom module is sufficient -- but more custom modules seem to make the bug more likely to appear.

After running waybar, the following script can be used to trigger the issue:
```bash
for i in $(seq 1 10); do
	hyprctl keyword monitor "eDP-1,disable"
	hyprctl keyword monitor "eDP-1,3072x1920@120.00Hz,0x0,1.5"
	sleep 1
done
```

You may need to update display names and some other flags according to your setup.

Given that a persistent custom module seem to be required to reproduce the issue, I am now suspecting that something is trying to terminate the programs executed as part of the custom modules, and accidentally triggering destruction of the IPC object as a result.

**Comment by zjeffer** [comment]
For some reason:
```
for i in $(seq 1 10); do
	hyprctl keyword monitor "eDP-1,disable"
	hyprctl keyword monitor "eDP-1,3072x1920@120.00Hz,0x0,1.5"
	sleep 1
done
```
Running this (modified with my second monitor instead of your laptop monitor) seems to kill all windows on my first monitor, and crash hyprpaper... Need to investigate more when I have time.

**Comment by lfos** [comment]
> Running this (modified with my second monitor instead of your laptop monitor) seems to kill all windows on my first monitor, and crash hyprpaper... Need to investigate more when I have time.

Interesting. Does it also happen when adding another `sleep` command between the two `hyprctl` commands; and maybe increase to 2-3 seconds? Are you still able to debug the waybar issue, despite the (likely unrelated) crashes?

**Comment by zjeffer** [comment]
The windows don't get killed when I sleep 1 second in between disabling and reenabling the monitor, but I can't reproduce the either. I also tried with virtual outputs like this:

```
hyprctl output create headless test && hyprctl output remove test
```
without any sleep, which also doesn't trigger the issue. 
Does it trigger for you with the above command instead of the for loop you use? Keep in mind to remove the output key in your config.json, so the bar is spawned on all monitors.

**Comment by zjeffer** [comment]
Also, have you done a git bisect on Waybar? Do you know for sure that it's caused by my changes in https://github.com/Alexays/Waybar/pull/3945?

**Comment by lfos** [comment]
I can reproduce the issue with an additional `sleep 1` in my original loop.

I can **not** reproduce the issue with your version using `hyprctl output create headless` + removed `output` field.

I think we've already established that removing the cleanup/destructor code introduced in commit 5b8839ab (Hyprland IPC improvements, 2025-02-19) fixes the issue; see https://github.com/Alexays/Waybar/issues/3975#issuecomment-3180713866. I don't think we can conclude the issue is caused only by the changes added in https://github.com/Alexays/Waybar/pull/3945 and there seems to be some evidence of multicausality; that said, at the very least, some part of the changes in that PR trigger the issue in cases where it wouldn't have been triggered otherwise.

**Comment by zjeffer** [comment]
> I think we've already established that removing the cleanup/destructor code introduced in commit https://github.com/Alexays/Waybar/commit/5b8839ab5cffb9dd8027588d749504df363569fe (Hyprland IPC improvements, 2025-02-19) fixes the issue

This simply indicates that something is calling the destructor when it shouldn't. We need to figure out what causes the destructor to trigger in the first place, but as I can't seem to reproduce it, can you try this:
1. compile waybar from my PR (https://github.com/Alexays/Waybar/pull/4359) **with** debug symbols (`meson setup build --wipe -Dbuildtype=debug && ninja -C build`)
2. launch waybar through gdb:  `gdb --args ./build/waybar --config your-minimal-config.jsonc -l debug` 
3. set a breakpoint at the Hyprland IPC destructor with `break waybar::modules::hyprland::IPC::~IPC` in the gdb console
4. Start waybar with `run` in the gdb console
5. trigger the issue, and get a backtrace when it breaks.

When I try the above steps + your minimal config & monitor reconnect script, gdb never breaks. I assume it will break on your setup, and then you can get a backtrace with `bt full`. This way we'll see what exactly is calling the destructor.

**Comment by lfos** [comment]
> > I think we've already established that removing the cleanup/destructor code introduced in commit [5b8839a](https://github.com/Alexays/Waybar/commit/5b8839ab5cffb9dd8027588d749504df363569fe) (Hyprland IPC improvements, 2025-02-19) fixes the issue
> 
> This simply indicates that something is calling the destructor when it shouldn't.

Sorry, this was just an explanation for how/why https://github.com/Alexays/Waybar/pull/3945 introduced (part of what's causing) the issue - the destructor didn't exist prior to that PR. I 100% agree that we should understand why the destructor is called instead of simply removing it again.
 
> 1. compile waybar from my PR ([Fix Hyprland IPC thread sanitizer warning, other IPC & general fixes #4359](https://github.com/Alexays/Waybar/pull/4359)) **with** debug symbols (`meson setup build --wipe -Dbuildtype=debug && ninja -C build`)
> 2. launch waybar through gdb:  `gdb --args ./build/waybar --config your-minimal-config.jsonc -l debug`
> 3. set a breakpoint at the Hyprland IPC destructor with `break waybar::modules::hyprland::IPC::~IPC` in the gdb console
> 4. Start waybar with `run` in the gdb console
> 5. trigger the issue, and get a backtrace when it breaks.
> 
> When I try the above steps + your minimal config & monitor reconnect script, gdb never breaks. I assume it will break on your setup, and then you can get a backtrace with `bt full`. This way we'll see what exactly is calling the destructor.

No, unfortunately, it doesn't break when `Hyprland IPC stopping...` is printed and the issue is triggered; while other breakpoints, such as on the constructor, work as intended. Very odd.

**Comment by lfos** [comment]
Note: If I add a manual backtrace() call to the destructor, I am getting this -

```
IPC destructor: 0x55f93bdae760 thread: 140660631918272
waybar(+0x12c359) [0x55f93bcad359]
/usr/lib/libc.so.6(+0x40cb1) [0x7fee90040cb1]
/usr/lib/libc.so.6(+0x40d8e) [0x7fee90040d8e]
/usr/lib/libc.so.6(+0x96a94) [0x7fee90096a94]
/usr/lib/libc.so.6(+0x11aa0c) [0x7fee9011aa0c]
```

Where:
* `0x12c359` is `waybar::modules::hyprland::IPC::~IPC() + 217 in section .text of /usr/bin/waybar`
* `0x40cb1` is `__run_exit_handlers + 497 in section .text of /usr/lib/libc.so.6`
* `0x96a94` is `start_thread + 948 in section .text of /usr/lib/libc.so.6`
* `0x11aa0c` is `__clone3 + 44 in section .text of /usr/lib/libc.so.6`

**Comment by zjeffer** [comment]
Just as a sanity check, can you check if there's more than 1 waybar process running:

```
pgrep -a waybar
```

**Comment by lfos** [comment]
> Just as a sanity check, can you check if there's more than 1 waybar process running:
> 
> ```
> pgrep -a waybar
> ```

Interesting. There's just one process before the issue is triggered -- but a second defunct child process appears once the issue arises. Before:

```
$ pgrep -a waybar
2167419 waybar
```

After:
```
$ pgrep -a waybar
2167419 waybar
2167740 [waybar] <defunct>
$ ps -o ppid= -p 2167740
2167419
```

Good find.

**Comment by lfos** [comment]
Assuming the destructor is called in the child process (which would explain a few observations made above, such as the breakpoint not being triggered), my understanding is that this still shouldn't impact the active parent waybar process?

**Comment by lfos** [comment]
Ok, I think I finally understand what's happening. Fix: https://github.com/Alexays/Waybar/pull/4408

@zjeffer - Thanks for all your debugging help/ideas!

**Comment by mindrunner** [comment]
Can we have a release with this fix please?
