### ISSUE TITLE
workspace 10 order is not correct

### ISSUE THREAD

**Issue by guanghwang** [Alexays/Waybar#482]
## Platform
```
arch Linux, sway 1.2-3, waybar 0.8.0-3
```

## Problem

The order of workspace 10 is not correct. It is not next to workspace 9. Instead, it is between workspace 1 and workspace 2. If I use sway-bar, workspace 10 is right next to workspace 9.

## How to reproduce
```
1. add workspace 10 in sway config
2. switch to workspace 10
3. It is between workspace 1 and workspace 2
```

I expect that workspace 10 is right next to workspace 9.

**Comment by Alexays** [comment]
It is because the comparison is made on a string so the 1 of 10 is taken into account, i'll look into that.

**Comment by Ventto** [comment]
I have tried with 10 workspaces (even with 11) and it seems to works  (c.f the screenshot below). Here is the sway config:

```
set $ws1 "1: A"
set $ws2 "2: B"
set $ws3 "3: C"
set $ws4 "4: D"
set $ws5 "5: E"
set $ws6 "6: F"
set $ws7 "7: G"
set $ws8 "8: H"
set $ws9 "9: I"
set $ws10 "10: J"

workspace $ws1
workspace $ws2
workspace $ws3
workspace $ws4
workspace $ws5
workspace $ws6
workspace $ws7
workspace $ws8
workspace $ws9
workspace $ws10
```
![waybar example](https://i.ibb.co/Q608nrS/region-2019-10-14-202723.png)

Can you share your configuration ?

**Comment by guanghwang** [comment]
I use the default config in sway. 

```
    bindsym $sup+1 workspace 1
    bindsym $sup+2 workspace 2
    bindsym $sup+3 workspace 3
    bindsym $sup+4 workspace 4
    bindsym $sup+5 workspace 5
    bindsym $sup+6 workspace 6
    bindsym $sup+7 workspace 7
    bindsym $sup+8 workspace 8
    bindsym $sup+9 workspace 9
    bindsym $sup+0 workspace 10
```
waybar config
```
    "sway/workspaces": {
        "disable-scroll": true,
        "format": "{name}:{icon}",
        "format-icons": {
            "1": "😎",
            "2": "🌐",
            "3": "📁",
            "4": "🤖",
            "5": "📝",
            "6": "📒",
            "7": "📖",
            "8": "🎸",
            "9": "📧",
            "10": "🌞"
        }
    },
```

**Comment by Alexays** [comment]
Should be fixed with 7f7ebb5367751c9c6eb82226c9168cf6e809d16c

**Comment by kchibisov** [comment]
Unfortunately this bug wasn't solved. The problem is that in when you're assigning a `string` to v["name"] it'll become a `"string"` on next read. So `v["name"] = string(10)`, will become `string("10")`.

You can observe it by applying following diff.
```diff
diff --git a/src/modules/sway/workspaces.cpp b/src/modules/sway/workspaces.cpp
index b65e47d..8bf6628 100644
--- a/src/modules/sway/workspaces.cpp
+++ b/src/modules/sway/workspaces.cpp
@@ -1,5 +1,6 @@
 #include "modules/sway/workspaces.hpp"
 #include <spdlog/spdlog.h>
+#include <iostream>

 namespace waybar::modules::sway {

@@ -33,6 +34,8 @@ void Workspaces::onEvent(const struct Ipc::ipc_response &res) {
   }
 }

+#include <cstdlib>
+
 void Workspaces::onCmd(const struct Ipc::ipc_response &res) {
   if (res.type == IPC_GET_WORKSPACES) {
     try {
@@ -55,6 +58,7 @@ void Workspaces::onCmd(const struct Ipc::ipc_response &res) {
           const std::vector<std::string> p_workspaces_names = p_workspaces.getMemberNames();

           for (const std::string &p_w_name : p_workspaces_names) {
+            std::cout << "NAME: " << p_w_name << std::endl;
             const Json::Value &p_w = p_workspaces[p_w_name];
             auto               it =
                 std::find_if(payload.begin(), payload.end(), [&p_w_name](const Json::Value &node) {
@@ -70,7 +74,7 @@ void Workspaces::onCmd(const struct Ipc::ipc_response &res) {
               for (const Json::Value &output : p_w) {
                 if (output.asString() == bar_.output->name) {
                   Json::Value v;
-                  v["name"] = p_w_name;
+                  v["name"] = std::atoi(p_w_name.c_str());
                   v["target_output"] = bar_.output->name;
                   workspaces_.emplace_back(std::move(v));
                   break;
@@ -79,18 +83,25 @@ void Workspaces::onCmd(const struct Ipc::ipc_response &res) {
             } else {
               // Adding to all outputs
               Json::Value v;
-              v["name"] = p_w_name;
+              v["name"] = std::atoi(p_w_name.c_str());
               v["target_output"] = "";
               workspaces_.emplace_back(std::move(v));
             }
           }

+          for (auto W : workspaces_) {
+            std::cerr << "W: " << W["name"] << "\n";
+          }
+
           std::sort(workspaces_.begin(),
                     workspaces_.end(),
                     [](const Json::Value &lhs, const Json::Value &rhs) {
+                      std::cerr << "LHS NAME: " << lhs["name"] << " RHS NAME: " << rhs["name"] << std::endl;
                       if (lhs["name"].isInt() && rhs["name"].isInt()) {
+                        std::cerr << "FINALLY INT\n";
                         return lhs["name"].asInt() < rhs["name"].asInt();
                       }
+                      std::cerr << "AS STRING CMP\n";
                       return lhs["name"].asString() < rhs["name"].asString();
                     });
         }

```
and my output for this diff

```
NAME: 1
NAME: 10
NAME: 2
NAME: 3
NAME: 4
NAME: 5
NAME: 6
NAME: 7
NAME: 8
NAME: 9
W: "1"
W: 10
W: 2
W: 3
W: 4
W: 5
W: 6
W: 7
W: 8
W: 9
LHS NAME: 10 RHS NAME: "1"
AS STRING CMP
LHS NAME: 10 RHS NAME: "1"
AS STRING CMP
LHS NAME: 2 RHS NAME: "1"
AS STRING CMP
LHS NAME: 2 RHS NAME: 10
FINALLY INT
LHS NAME: 2 RHS NAME: "1"
AS STRING CMP
LHS NAME: 3 RHS NAME: "1"
AS STRING CMP
LHS NAME: 3 RHS NAME: 10
FINALLY INT
LHS NAME: 3 RHS NAME: 2
FINALLY INT
LHS NAME: 4 RHS NAME: "1"
AS STRING CMP
LHS NAME: 4 RHS NAME: 10
FINALLY INT
LHS NAME: 4 RHS NAME: 3
FINALLY INT
LHS NAME: 5 RHS NAME: "1"
AS STRING CMP
LHS NAME: 5 RHS NAME: 10
FINALLY INT
LHS NAME: 5 RHS NAME: 4
FINALLY INT
LHS NAME: 6 RHS NAME: "1"
AS STRING CMP
LHS NAME: 6 RHS NAME: 10
FINALLY INT
LHS NAME: 6 RHS NAME: 5
FINALLY INT
LHS NAME: 7 RHS NAME: "1"
AS STRING CMP
LHS NAME: 7 RHS NAME: 10
FINALLY INT
LHS NAME: 7 RHS NAME: 6
FINALLY INT
LHS NAME: 8 RHS NAME: "1"
AS STRING CMP
LHS NAME: 8 RHS NAME: 10
FINALLY INT
LHS NAME: 8 RHS NAME: 7
FINALLY INT
LHS NAME: 9 RHS NAME: "1"
AS STRING CMP
LHS NAME: 9 RHS NAME: 10
FINALLY INT
LHS NAME: 9 RHS NAME: 8
FINALLY INT

```

I've launched Waybar only having active Workspace 1, so it was filtered and missed my `atoi` conversion(I'm not proposing `atoi` to solve this problem, just an example). And during cmp you can see that I'm comparing string `"1"` to `8`. I guess we either should drop begin/end `"` and try converting to int and then cmp it or store ints direcly.

**Comment by guanghwang** [comment]
The order in the new version does not work again.

![image](https://user-images.githubusercontent.com/12839553/73408778-529c7100-42cb-11ea-9bc6-2ed3a2b4cdee.png)

Here is the config of waybar
```
    "sway/workspaces": {
        "persistent_workspaces": {
            "1": ["eDP-1", "'Dell Inc. DELL P2012H 8VVND24OCSWS'"]
        },
        "disable-scroll": true,
        "format": "{name}:{icon}",
        "format-icons": {
            "1": "",
            "2": "",
            "3": "",
            "4": "",
            "5": "",
            "6": "",
            "7": "",
            "8": "",
            "9": "",
            "10": ""
        }
    },


```

**Comment by dschrempf** [comment]
For me, the order works when I do not specify "peristent_workspaces". If I specify all my workspaces, they get ordered in the wrong way. I use workspace names of the form `index:name`, so for example, `10:0`, or `11:-`.

**Comment by guanghwang** [comment]
> For me, the order works when I do not specify "peristent_workspaces". If I specify all my workspaces, they get ordered in the wrong way. I use workspace names of the form `index:name`, so for example, `10:0`, or `11:-`.

Thanks for the workaround. After I commented persistent_workspaces, the order is correct. I will live with this for now.

**Comment by Alexays** [comment]
Sure, will check!

**Comment by Alexays** [comment]
Ok figured why, [here](https://github.com/Alexays/Waybar/blob/master/src/modules/sway/workspaces.cpp#L97), isInt will never enter cause of it's defined as a string, we need to try to convert int before.

**Comment by Alexays** [comment]
Fixed with #696

**Comment by meklonets** [comment]
Hello, 
Faced with the wrong order issue for the F1-F10 workspaces. 
```
set $ws1 1:Termite
set $ws2 2:WEB
set $ws3 3:Telegram
set $ws4 4:Files
set $ws5 5:KeePassXC
set $ws6 6:RTS
set $ws7 7:Chromium
set $ws8 8:Transmission
set $ws9 9:VM
set $ws10 10:Jami
set $wsF1 F1:P
set $wsF2 F2:STS
set $wsF3 F3:GVoice
set $wsF4 F4
set $wsF5 F5:RDP
set $wsF6 F6
set $wsF7 F7
set $wsF8 F8
set $wsF9 F9
set $wsF10 F10:MCN
```
Workspaces from 1 to 10 get proper order in waybar. But F1-F10 appears on the right next to previous opened one.
![11h_17m_52s_28_Apr_22](https://user-images.githubusercontent.com/13570880/165710788-ea9ce702-57fe-43c5-8a5a-39482c2b1563.png)

**Comment by Esensats** [comment]
For people looking for custom ordering stumbling upon this issue look into [this PR](https://github.com/Alexays/Waybar/pull/4536/)
