### ISSUE TITLE
[BUG] format-alt  not working in pulseaudio module if format-muted is also present

### ISSUE THREAD

**Issue by libXq** [Alexays/Waybar#591]
When using "format-muted" with the pulseaudio module, format-alt (right click to change between format and format-alt) wont work.

format-alt not working:

```
    "pulseaudio": {
        "format": "{icon}",
        "format-alt": "{icon} {volume}%",
        "format-muted": "",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", ""]
        },
        "scroll-step": 1,
        "smooth-scrolling-threshold": 5,
        "on-click-right": "pactl set-sink-mute @DEFAULT_SINK@ toggle",
        "tooltip": false
    },
```

by removing "format-muted", now "format-alt" works, but fortunately losing "format-muted" 

```
    "pulseaudio": {
        "format": "{icon}",
        "format-alt": "{icon} {volume}%",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", ""]
        },
        "scroll-step": 1,
        "smooth-scrolling-threshold": 5,
        "on-click-right": "pactl set-sink-mute @DEFAULT_SINK@ toggle",
        "tooltip": false
    },
```

any Idea how to get both working together?

**Comment by Alexays** [comment]
Should be fixed on master with #592

**Comment by libXq** [comment]
using waybar v0.9.2

If format-alt is active, pulseaudio-module don't update if signal is sent, it stays unmuted. Logically, it should change its icon to not muted/normal. You can test it by a leftclick to change to format alt, afterwards right-click on the module, it stays unchanged.

config:
` 
 "pulseaudio": {
    "format": "{icon}",
    "format-alt": "{icon} {volume}%",
    "format-muted": "",
    "format-icons": {
      "headphone": "",
      "hands-free": "",
      "headset": "",
      "phone": "",
      "portable": "",
      "car": "",
      "default": ["", ""]
    },
    "on-click-right": "pactl set-sink-mute @DEFAULT_SINK@ toggle",
    "smooth-scrolling-threshold": 5,
    "tooltip": false
  },
`

**Comment by exoess** [comment]
still having this issue, will it get fixed or do i just have to deal with it lol
