### ISSUE TITLE
Clock module "%P" shows literal %P, not am/pm

### ISSUE THREAD

**Issue by jake-is-a-legend** [Alexays/Waybar#614]
This used to work before the last update. The issue remains with an empty config. Set your waybar config to the code below to reproduce the issue:
```
{
    "modules-left": ["clock"],
    "clock": {"format": "{:%P}"}
}
```

note: lowercase `%p` works even though `%P` doesn't.

**Comment by jake-is-a-legend** [comment]
fix your shit wtf

**Comment by Alexays** [comment]
That's what we call supporting open source, sadly...
Fixed with #715 unless timezone is specified.
While waiting for a [HowardHinnant/date](https://github.com/HowardHinnant/date) update.

**Comment by P1n3appl3** [comment]
Sorry to gravedig this issue, but I think the original problem wasn't actually resolved by #715. The `%P` flag is supported by `strftime`/`date` but not by the `fmt` chrono formatting. It doesn't seem to hard to write a custom module that just calls `date`, but it'd be nice if `%P` were handled by the default clock module.
