### ISSUE TITLE
Paths with environment variables are non-working

### ISSUE THREAD

**Issue by McAllaster** [Alexays/Waybar#710]
I'm unable to utilize environment variables like `$HOME` (or its shortcut `~`) working in supplied paths for modules (like with temperature's `hwmon-path` option).

_"Why is this useful?"_ you may ask. Here's my situation:

I use my configuration for multiple machines/users, and files for temperature are located at different sources. To solve this, I symbolically link the appropriate temperature files into a user's home directory as `.cpu_temperature` and `.gpu_temperature`, and then reference those. This has worked in things like i3bar, but with waybar being unable to use the `$HOME` environment variable I am left wanting.

If there is another solution to this, I would be grateful to hear it.

**Comment by Alexays** [comment]
Should be fixed on master 😄 
Can you test?

**Comment by McAllaster** [comment]
Just cloned and built `Waybar v0.9.2-92-g6ca4e14 (May 23 2020, branch 'master')` and this is still not working for me.

The following is a minimal config, confirmed not working:
```
{
    "modules-right": ["temperature"],
    "temperature": {
        "hwmon-path": "~/.cpu_temperature"
    }
}
```

Replacing `~/.cpu_temperature` with `$HOME/.cpu_temperature` similarly does not work, while an absolute path `/home/myusername/.cpu_temperature` _does_ work.

**Comment by Alexays** [comment]
Ok, i thought it was a custom module.
Will reopen the issue :)
