### ISSUE TITLE
Failed to acquire required resources.

### ISSUE THREAD

**Issue by oskarsh** [Alexays/Waybar#893]
Running Fedora Beta 33 with Gnome. I wanted to try out Waybar but it keeps crashing. The path to the ressource file is correct.

**Comment by Alexays** [comment]
Should be fixed with latest version

**Comment by tasmo** [comment]
@Alexays Unfortunately it is still an issue with Gnome 40 on Fedora 34.

`waybar -l trace` just gives me this output:

```sh
[2021-05-10 13:14:34.037] [info] Resources files: /home/user/.config/waybar/config, /home/user/.config/waybar/style.css
[2021-05-10 13:14:34.039] [error] Failed to acquire required resources.
```

The files do exist and even when I tell Waybar to use them with `-c` and `-s` it doesn' t work.
